mirage/mirage

- lib/main.ml
- lib/mirage.ml
- lib/mirage.mli
Just a proof of concept, not tested at all so might not be working as expected.
> Test the opam version

- lib/mirage.ml
See #350 and mirage/mirage-tcpip#100.
> Fix STACKV4 code gen for DEVICE sig w/o 'connect'

- types/V1.mli
No semantics change, just cut long lines, add section headers and rewrite few wordings. Could be still improved, though.
> Improve docs

- lib/mirage.ml
- lib/mirage.mli
I've aslo deleted some dead code.
> Adapt to latest changes in conduit and mirage-http

- .travis-ci.sh
- .travis.yml
- lib/main.ml
- lib/mirage.ml
- lib/mirage.mli
This is useful if you don't have root access, since otherwise mirage
tries to run sudo and fails.
Closes: #401
> Add --no-depext flag

- types/V1.mli
Add some words to docstrings about the expected behavior of some functions in the FS module type.
> docs: clarify some expected behaviour for FS module type

- types/V1.mli
this goes well with https://github.com/mirage/mirage-tcpip/pull/164
> fix documentation regarding changes in https://github.com/mirage/mirage-tcpip/pull/164

- lib/mirage.ml
- lib/mirage.mli
- lib/mirage_key.mli
Something I considered including: making keys (such as dhcp and net) generate an env variable by default. I feel slightly uneasy about this, but it seems to be rather common. What would you prefer ?
> Misc improvements

- lib/mirage.ml
- lib/mirage.mli
- lib/mirage_key.ml
- lib/mirage_key.mli
> Restore previous tracing API

- lib/mirage.ml
Also see https://github.com/mirage/functoria/pull/44
> Temporary hack to fix tracing.

- Dockerfile
With this,
`docker run -it -v ~/src/mirage-skeleton:/src mirage` works great
> refresh Dockerfile to use latest supported OPAM images

- lib/mirage.ml
Remove camlp4 tags, add debug and warnings.
> Clean-up ocamlbuild tags

- .travis.yml
- lib/mirage.ml
> Make all projects depend on mirage-platform

- mirage-types.opam
See ocaml/opam-repository#6331. Please delete branch after merging/closing.
> opam: add ocamlbuild build dependency

- .travis.yml
also remove unneeded pins to @yomimono branch now that it is merged
> test also with 4.03

- lib/mirage.ml
- lib/mirage.mli
> Consistent kvro

- .travis.yml
- lib/mirage.ml
- lib/mirage_key.ml
- lib/mirage_key.mli
This is a manual merge of
76575138f27ccfbff2a073ba997c54d4afb84149..6ea671335a71e0f90e2c6b4933a2b830dcb88106
(from djwillia/mirage.git#solo5) and some massaging
Author: Dan Williams <djwillia@us.ibm.com>
Author: Martin Lucina <martin@lucina.net>
Author: Hannes Mehnert <hannes@mehnert.org>
please compare https://github.com/djwillia/mirage/compare/master...djwillia:solo5?expand=1
> Solo5 changes (new platform `Ukvm and `Virtio).

- lib/mirage.ml
- lib/mirage.mli
- types/V1.mli
- types/V1_LWT.mli
This is a resubmission of #548 with a few more commits appended to make `mirage configure` do the right thing.
> New clock api

- lib/mirage.ml
@Drup noted the missing dependency, thanks!
> shuffle around to add a dependency to nocrypto_entropy to nocrypto_rng

- _tags
- lib/mirage.ml
- mirage-types.opam
- mirage.opam
- pkg/META.mirage
- pkg/META.mirage-types
- pkg/pkg.ml
- types/V1.mli
- types/mirage-types.mllib
- types/runtime/m_pp.ml
- types/runtime/m_pp.mli
see https://github.com/mirage/mirage-dev/pull/166
> Network error

- Dockerfile.doc
Also adds a few ppx packages into the mix that we use for web
stuff (like tyxml-ppx)
> Refresh doc gen to be a sorted list for upcoming trove

- Dockerfile.doc
Includes my changes and @hannesm
> Doc refresh

- Dockerfile.doc
https://github.com/ocaml/opam-repository/pull/7736 @avsm
> add solo5 libs now that we can install it together with xen

- .travis.yml
Specific targets chosen largely arbitrarily; if you'd like to change them, please speak up.  We'll be able to test across a larger set of targets when not limited by Travis-CI's organization-wide concurrent test limit.
> Add a smattering of 4.04 build tests.

- Dockerfile.doc
- lib/mirage.ml
to be merged with https://github.com/mirage/mirage-console/pull/45 -- see travis results (all green!) in https://github.com/mirage/mirage-dev/pull/205
> adjust to new mirage-console-* package layout

- lib/mirage.ml
Depends on mirage/mirage-clock#21.
> Rename mirage-clock-xen to -freestanding

- lib/mirage.ml
the `let minor, major = Cmd.ocaml_version ()` swaps `minor` and `major`.  There is additionally a piece of code which checks for >=OCaml-4.02.3... Thus this piece of code is never executed, and can be removed.
> don't generate a myocamlbuild.ml anymore. was needed for old OCaml 4.0

- lib/mirage.ml
see https://github.com/mirage/functoria/pull/85
> no need to manually add targets to makefile

- Dockerfile.doc
these are mainly misc additions and some are transitive dependencies
> docs: remove nbd for now (broken in dev) and add more dependents

- lib/mirage.ml
some systems have limited space for naming, and this "mir-" looks strange to me
see e.g. https://github.com/Solo5/solo5/issues/141 -- but if there are any good arguments to keep a `mir-` prefix, please discuss.
> remove "mir-" prefix from build products.

- README.md
> make README less Xen-partisan

- .travis.yml
This reverts commit 4f4c16b9c2fb8f53b9a610602fc4fcecc12f0fde.
> Revert "TMP: use my fork of mirage-dev"

- _tags
> Fix the compilation of mirage-types

- Dockerfile.doc
see mirage/mirage-dev#287 for the channel renaming
> doc: add new mirage packages and rename channel

- Dockerfile.doc
> doc: disable some broken trunk packages to get a rebuild working

- Dockerfile.doc
- lib/mirage.ml
to be merged with https://github.com/mirage/mirage-random/pull/3
> mirage-stdlib-random was subsumed into mirage-random

- lib/mirage.ml
> fix tar invocations for making archives

- lib/mirage.ml
Accounts for future flexibity in final link runes for Solo5 targets by
adding an "ldpostflags" pkg-config variable, the contents of which (if
present) are appended to the end of the final link command.
Also fixes a potential bug in the `pkg_config` callout function where
the result should be an empty list if the output is empty.
> Add an "ldpostflags" variable for Solo5 targets

- Dockerfile.doc
> doc: pin odoc to a known working version

- lib/mirage.ml
> add a depends target to the generated Makefile

- lib/mirage.ml
(`TERM <> "dumb" && Unix.isatty stdout`), if this is the case, pass `color(always)`
this is a slightly advanced fix for #797 which should make more people happy (I like colors).  motivation is that the potential fix upstream in OCaml will take some time, and adding 5 lines to have colored output for most people is worth it IMHO.
> instead of removing all the colors, check whether the output is a tty

- Dockerfile.doc
until https://github.com/vbmithr/ocaml-websocket/issues/84 is fixed
cc @vbmithr
> docs: remove websocket from the docs.mirage.io build list

- CHANGES.md
- lib/mirage.ml
> Link io-page-unix on Ukvm and Virtio too

- lib/mirage.ml
> Fix a warning when connecting a ramdisk

- .travis.yml
- lib/mirage.ml
- mirage.opam
> Adapt to latest functoria

- .travis.yml
charrua.0.9 and functoria.2.2.0 have been released.
> travis: remove PINS on charrua and functoria

- CHANGES.md
> Prepare to release 3.0.5 again

- .travis-ci.sh
- .travis.yml
- lib/mirage.ml
Related to [mirage/ocaml-cohttp#572]
> Rename mirage-http to cohttp-mirage

- lib/mirage.ml
Fixes https://github.com/mirage/mirage/issues/796 .
> fix lwt tracing hint (& an `ocamlfind query` invocation bug)

- .travis.yml
- lib/mirage.ml
and not as 3.0.0.  the most recent mirage (3.0.6) won't work :(
> cohttp-mirage is released as 1.0.0

- CHANGES.md
> Prepare to release 3.0.7

- .travis-ci.sh
now that mirage-skeleton muen-ready is merged :D
> use mirage-skeleton master again

- lib/mirage.ml
to solve (1b) //cc @linse @rjbou @marmarek
> Add mirage dependency to all the generated unikernels

- lib/mirage_impl_arpv4.ml
- lib/mirage_impl_ethernet.ml
- lib/mirage_impl_ip.ml
> require tcpip 3.6.0 - 3.7.0

- lib/mirage_impl_random.ml
- lib/mirage_key.ml
- lib/mirage_key.mli
and improve documentation of PRNG key
> Mirage_key: remove ?group parameter from PRNG, there's only one PRNG

- .travis-ci.sh
- .travis.yml
- lib/mirage.ml
- lib/mirage.mli
- lib/mirage_impl_arpv4.ml
- lib/mirage_impl_ethernet.ml
- lib/mirage_impl_ip.ml
- lib/mirage_impl_network.ml
- mirage-types-lwt.opam
- mirage-types.opam
- types/mirage_types.ml
- types/mirage_types_lwt.ml
see https://github.com/mirage/mirage-protocols/pull/16
> rename ethif to ethernet

- mirage-types-lwt.opam
- types/dune
seems to be needed in mirage<3 days...
> no need for io-page in mirage-types-lwt

- CHANGES.md
will merge this and #990 tomorrow and cut a release unless someone objects //cc @mirage/core
> changes for 3.5.1

- .travis.yml
- lib/mirage.ml
- lib/mirage_impl_argv.ml
- lib/mirage_impl_block.ml
- lib/mirage_impl_console.ml
- lib/mirage_impl_ip.ml
- lib/mirage_impl_kv.ml
- lib/mirage_impl_network.ml
- lib/mirage_impl_random.ml
- lib/mirage_impl_tracing.ml
- lib/mirage_key.ml
- lib/mirage_key.mli
These are the `mirage` front-end changes for #992.
> Solo5: "spt" target, application manifest generation, multiple devices support

- lib/mirage.ml
Delete all OPAM file when we `mirage configure` and avoid duplicate. Not sure if it's exactly the right direction.
> Clean *.opam file when we configure a new target

- .travis-ci.sh
- .travis.yml
- lib/mirage.ml
- lib/mirage.mli
- lib/mirage_impl_argv.ml
- lib/mirage_impl_arpv4.ml
- lib/mirage_impl_block.ml
- lib/mirage_impl_conduit_connector.ml
- lib/mirage_impl_console.ml
- lib/mirage_impl_ethernet.ml
- lib/mirage_impl_fs.ml
- lib/mirage_impl_ip.ml
- lib/mirage_impl_kv.ml
- lib/mirage_impl_mclock.ml
- lib/mirage_impl_network.ml
- lib/mirage_impl_pclock.ml
- lib/mirage_impl_qubesdb.ml
- lib/mirage_impl_random.ml
- lib/mirage_impl_reporter.ml
- lib/mirage_impl_resolver.ml
- lib/mirage_impl_resolver.mli
- lib/mirage_impl_syslog.ml
- lib/mirage_impl_tcp.ml
- mirage-runtime.opam
- mirage-types-lwt.opam
- mirage-types.opam
- mirage.opam
- types/dune
- types/mirage_types.ml
- types/mirage_types_lwt.ml
~~this is a draft until the interfaces are actually out there~~
> adapt to 1004 changes of the interfaces

- functoria/app/functoria_app.ml
- functoria/lib/functoria_engine.ml
- functoria/lib/functoria_engine.mli
- functoria/lib/functoria_graph.mli
>  Move Functoria_engine in functoria (from functoria.app) and document it

- types/mirage_types.ml
See https://github.com/ocaml/ocaml/pull/1237#issuecomment-315856786
> Silence the deprecation warning of the deprecations we propagate anyway

- lib/functoria/action.ml
- lib/functoria/action.mli
- lib/functoria/app.ml
- lib/functoria/cli.ml
- lib/functoria/cli.mli
- test/f0/f0.ml
- test/functoria-query/dune
- test/functoria-query/files-build.expected
- test/functoria-query/files-configure.expected
These commands allow to query the list of files generated by the configure and build steps.
On top of #1080
> functoria: add `<cmd> query files-configure` and `<cmd> query files-build`

- test/functoria-test/dune
- test/functoria-test/functoria_test.ml
- test/functoria-test/functoria_test.mli
- test/functoria/gen-1/dune
- test/functoria/gen-1/main.ml.expected
- test/functoria/gen-1/test.ml
- test/functoria/gen-2/dune
- test/functoria/gen-2/main.ml.expected
- test/functoria/gen-2/test.ml
- test/mirage/info_gen/dune
- test/mirage/info_gen/main.ml.expected
- test/mirage/info_gen/test.ml
> Add a functoria-test library to avoid code duplication

- lib/functoria/context.ml
- lib/functoria/context.mli
- lib/functoria/key.ml
- lib/functoria/key.mli
- lib/functoria/misc.mli
- test/functoria/test_key.ml
On top of #1091 (and extracted from #1085)
> Rename Functoria.Misc.Unix into Functoria.Context

- lib/functoria/app.ml
- lib/functoria/context_cache.ml
- lib/functoria/context_cache.mli
- test/functoria/e2e/test.ml
> Move context caching functions to Functoria.Context_cache

- test/mirage/random-unix/dune
- test/mirage/random-unix/main.ml.expected
- test/mirage/random-unix/test.ml
- test/mirage/random-xen/dune
- test/mirage/random-xen/main.ml.expected
- test/mirage/random-xen/test.ml
> More uses of functoria-test in the tests

- test/functoria/help/config.ml
- test/functoria/help/configure-help.out.expected
- test/functoria/help/dune
- test/functoria/help/help-configure.out.expected
> Add tests for `<cmd> help` and `<cmd> x --help`

- lib/functoria/key.ml
- lib/functoria/key.mli
- lib/mirage/mirage.ml
- lib/mirage/mirage_impl_ip.ml
- lib/mirage/mirage_impl_misc.ml
- lib/mirage/mirage_impl_network.ml
- lib/mirage/mirage_impl_random.ml
- lib/mirage/mirage_impl_reporter.ml
- lib/mirage/mirage_impl_resolver.ml
- lib/mirage/mirage_impl_stackv4.ml
- lib/mirage/mirage_impl_syslog.ml
- lib/mirage/mirage_impl_tcp.ml
- lib/mirage/mirage_impl_tracing.ml
- lib/mirage/mirage_impl_udp.ml
- lib/mirage/mirage_key.mli
- test/f0/f0.ml
- test/functoria/functoria-query/config.ml
- test/functoria/gen-2/test.ml
- test/functoria/help/config.ml
- test/functoria/test_key.ml
- test/mirage/action/test.ml
- test/mirage/info_gen/test.ml
- test/mirage/random-xen/test.ml
This one is *not* extracted from #1085 but I really wanted to do it for a loooong time :-)
> Deprecate Functoria.Key.abstract in favor of Functoria.Key.v

- lib/functoria/action.ml
- lib/functoria/action.mli
- lib/functoria/app.ml
- test/functoria/test_action.ml
> Improve the Functoria.Action API

- lib/functoria/app.ml
- lib/functoria/cli.ml
- lib/functoria/cli.mli
- lib/functoria/context_cache.ml
- test/functoria/test_cli.ml
> functoria: improve the Functoria.Cli API

- test/f0/f0.mli
> tests: add an mli for F0

- lib/functoria/context_cache.ml
- lib/functoria/info.ml
- lib/functoria/key.ml
- test/functoria/e2e/test.ml
- always print the command being tested
- always add -vv
- minor tweaks to the log output to make them easier to read
Extracted from #1085
> functoria: improve the output of the e2e tests

- test/functoria/e2e/test.ml
Still extracted from #1085  (and follow-up of #1111)
> functoria: more minor cleanups to e2e tests

- lib/functoria/action.ml
- lib/functoria/action.mli
- test/functoria/test_action.ml
> Better handling of stout/stderr in Functoria.Action.run_cmd

- lib/functoria/action.ml
- lib/functoria/lib.ml
- lib/functoria/tool.ml
- test/functoria/test_action.ml
- test/functoria/tool/build-help-no-config.err.expected
- test/functoria/tool/build-help-no-config.expected
- test/functoria/tool/build.err.expected
- test/functoria/tool/clean.err.expected
- test/functoria/tool/configure-help.err.expected
- test/functoria/tool/configure.err.expected
- test/functoria/tool/describe.err.expected
- test/functoria/tool/dune
- test/functoria/tool/dune.inc
- test/functoria/tool/gen.ml
- test/functoria/tool/help-configure.err.expected
- test/functoria/tool/help-no-config-err.err.expected
- test/functoria/tool/help-no-config.err.expected
- test/functoria/tool/help-no-config.expected
- test/functoria/tool/help.err.expected
- test/functoria/tool/query.err.expected
- test/functoria/tool/simple-help.err.expected
- test/functoria/tool/test.ml
- test/functoria/tool/version.err.expected
> functoria: add tests for Functoria.Tool

- test/functoria/query/dune
- test/functoria/query/dune.inc
- test/functoria/query/gen.ml
> functoria: autogen the dune file for query tests

- lib/functoria/cli.ml
- lib/functoria/cli.mli
- test/functoria/test_cli.ml
> functoria: add argv transformer functions in Functoria.Cli

- lib/functoria/lib.ml
- lib/functoria/tool.ml
- test/functoria/query/files-configure.expected
- test/functoria/tool/configure-help.err.expected
- test/functoria/tool/configure.err.expected
Related to #1085 and cleaned up version of #1118
> functoria: generate .install files in Tool instead of Lib

- lib/functoria/cli.ml
- lib/functoria/cli.mli
- lib/functoria/lib.ml
- lib/functoria/makefile.ml
- lib/functoria/makefile.mli
- lib/functoria/tool.ml
- lib/mirage/mirage_clean.ml
- lib/mirage/mirage_configure.ml
- lib/mirage/mirage_configure.mli
- test/functoria/help/configure-help.out.expected
- test/functoria/help/help-configure.out.expected
- test/functoria/query/Makefile.depext.expected
- test/functoria/query/Makefile.expected
- test/functoria/query/dune.inc
- test/functoria/query/gen.ml
- test/functoria/test_cli.ml
- test/functoria/tool/configure-help.err.expected
- test/functoria/tool/configure.err.expected
- test/mirage/action/test.expected
This was done by mirage before -- move this into functoria for
better control.
> functoria: generate a toplevel Makefile when calling `<tool> configure'

- lib/functoria/action.ml
- lib/functoria/info.ml
- lib/functoria/install.ml
- lib/functoria/job.ml
- lib/functoria/key.ml
- lib/functoria/lib.ml
- lib/functoria/opam.ml
- test/functoria/gen-2/key_gen.ml.expected
> functoria: minor improvements to the log and code outputs

- lib/functoria/tool.ml
> functoria: fix the generation of opam and install names

- .travis.yml
> lint .travis.yml

- test/functoria/query/dune.inc
- test/functoria/query/gen.ml
> functoria: also track stderr for query tests

- lib/functoria/action.ml
- lib/functoria/action.mli
> Functoria.Action: do not trim the output of Action.run

- CHANGES.md
- functoria-runtime.opam
- functoria.opam
- lib/functoria/opam.ml
- lib/mirage/mirage.ml
- lib/mirage/mirage_build.ml
- lib/mirage/mirage_configure.ml
- lib/mirage/mirage_configure_solo5.ml
- lib/mirage/mirage_configure_solo5.mli
- lib/mirage/mirage_configure_xen.ml
- lib/mirage/mirage_configure_xen.mli
- lib/mirage/mirage_impl_argv.ml
- lib/mirage/mirage_impl_block.ml
- lib/mirage/mirage_impl_console.ml
- lib/mirage/mirage_impl_ip.ml
- lib/mirage/mirage_impl_misc.ml
- lib/mirage/mirage_impl_misc.mli
- lib/mirage/mirage_impl_network.ml
- lib/mirage/mirage_impl_qubesdb.ml
- lib/mirage/mirage_link.ml
- mirage-runtime.opam
- mirage-types-lwt.opam
- mirage-types.opam
- mirage.opam
- test/functoria/query/opam.expected
- test/mirage/action/test.expected
- test/mirage/query/opam-hvt.expected
- test/mirage/query/opam.expected
- test/mirage/query/packages-hvt.expected
- test/mirage/query/packages.expected
this syncs the changes on the 3 branch back to master.
> Xen pvh via solo5 for master

- CHANGES.md
- lib/mirage/mirage_key.ml
adapts #1205 to master, and includes the changes entry
> Fix ip address

- .ocamlformat
- .travis-ci.sh
- CHANGES.md
- dune-project
- lib/mirage_impl_ip.ml
- lib/mirage_impl_random.ml
this is fine for the next mirage-3 release
> mirage-crypto-rng will soon have 0.9.0 release without API changes

- lib/mirage.mli
- lib/mirage_impl_conduit.ml
- lib/mirage_impl_conduit.mli
- lib/mirage_impl_resolver.ml
- lib/mirage_impl_resolver.mli
- lib/mirage_key.ml
- lib/mirage_key.mli
> Upgrade conduit to 4.0.0

- CHANGES.md
- lib/mirage/impl/mirage_impl_conduit.ml
- lib/mirage/impl/mirage_impl_conduit.mli
- lib/mirage/impl/mirage_impl_random.ml
- lib/mirage/impl/mirage_impl_resolver.ml
- lib/mirage/impl/mirage_impl_resolver.mli
- lib/mirage/mirage.mli
- lib/mirage/mirage_key.ml
- lib/mirage/mirage_key.mli
- test/mirage/random-unix/main.ml.expected
- test/mirage/random-unix/test.ml
- test/mirage/random-xen/main.ml.expected
- test/mirage/random-xen/test.ml
From PRs:
- https://github.com/mirage/mirage/pull/1221
- https://github.com/mirage/mirage/pull/1223
And @hannesm's commit https://github.com/mirage/mirage/commit/f69d7276036489b47644ecc533d322d9b605482b
To be merged with https://github.com/mirage/mirage-skeleton/pull/302
> Integrate mirage 3.10.3 and 3.10.4 changes

- .ocamlformat
- lib/functoria/action.ml
- lib/functoria/cli.ml
- lib/functoria/filegen.ml
- lib/functoria/impl.ml
- lib/functoria/info.ml
- lib/functoria/key.ml
- lib/functoria/lib.ml
- lib/functoria/tool.ml
- lib/mirage/impl/mirage_impl_conduit.mli
- lib/mirage/impl/mirage_impl_kv.ml
- lib/mirage/impl/mirage_impl_misc.ml
- lib/mirage/impl/mirage_impl_resolver.ml
- lib/mirage/impl/mirage_impl_stack.ml
- lib/mirage/mirage.ml
- lib/mirage/mirage.mli
- lib/mirage/mirage_key.ml
- lib_runtime/mirage/mirage_runtime.ml
- test/functoria/help/dune
- test/functoria/query/dune
- test/mirage/help/dune
- test/mirage/query/dune
Upgrade the codebase to `ocamlformat.0.18.0`
> Upgrade to ocamlformat.0.18.0

- CHANGES.md
> add changes for 3.10.7 to main

- lib/functoria/cli.ml
- lib/functoria/cli.mli
- lib/functoria/lib.ml
- lib/functoria/makefile.ml
- lib/functoria/makefile.mli
- test/functoria/e2e/help.t
- test/functoria/help/configure-o.t
- test/functoria/help/configure.t
- test/functoria/help/query.t
- test/functoria/lib/run.t
- test/functoria/query/run.t
- test/functoria/test_cli.ml
- test/mirage/help/configure-o.t
- test/mirage/help/configure.t
- test/mirage/help/query.t
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
This PR adds our `dune-universe/mirage-opam-overlays` in any cases to be sure that we bring our `zarith+dune` package.
> Ensure to add in any case our mirage overlays

- CHANGES.md
- functoria-runtime.opam
- functoria.opam
- mirage-runtime.opam
- mirage.opam
- test/f0/dune
- test/functoria/context/dune
- test/functoria/e2e/dune
- test/functoria/errors/dune
- test/functoria/help/dune
- test/functoria/lib/dune
- test/functoria/query/dune
- test/functoria/tool/dune
- test/mirage-runtime/dune
- test/mirage/action/dune
- test/mirage/help/dune
- test/mirage/query/dune
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run.t
> Prepare v4.0.0~beta1

- lib/mirage/impl/mirage_impl_block.ml
- lib/mirage/impl/mirage_impl_block.mli
- lib/mirage/mirage.ml
- lib/mirage/mirage.mli
Be able to choose a specific branch when we want to craft a `docteur` image from a Git repository.
> Be able to choose a specific branch when we want to make a docteur image from a Git repository

- lib/mirage/mirage_key.ml
> remove ukvm warning

- lib/mirage/impl/mirage_impl_block.ml
- lib/mirage/impl/mirage_impl_block.mli
- lib/mirage/mirage.ml
- lib/mirage/mirage.mli
/cc @yomimono, it's a draft, feel free to complete/change/update the signature/documentation.
> Add chamelon device

- lib/functoria/lib.ml
- lib/functoria/makefile.ml
- lib/functoria/opam.ml
- lib/functoria/package.ml
- lib/mirage/mirage.ml
- test/functoria/context/run.t
- test/functoria/e2e/describe.t
- test/functoria/query/run.t
- test/functoria/test_package.ml
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
- test/opam-monorepo/lock.t
this is a follow up to bdb8921ff6d23a10243743daac2073279bbf01a1
To test with: https://github.com/mirage/mirage-skeleton/pull/343
> various makefile and opam file tweak

- lib/functoria/key.ml
- lib/functoria/key.mli
> Fix the separator for list and pair combinator

- lib/functoria/dune.ml
- test/functoria/query/run.t
- test/functoria/tool/run.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
> remove -warn-error -A from generated dune files

- lib/mirage/mirage.mli
I went over mirage.mli and updated things that had gone out of date and improved the documentation.
> Brush up mirage.mli

- .ocamlformat
- lib/functoria/lib.ml
- lib/functoria/makefile.ml
- lib/functoria/makefile.mli
- test/functoria/query/run.t
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
> Pass -f <config-file> in build rule of Makefile

- .ocamlformat
- lib/functoria/action.ml
- lib/functoria/key.mli
- lib/functoria/package.mli
- lib/mirage/impl/mirage_impl_git.ml
- lib/mirage/mirage.ml
- lib/mirage/mirage.mli
- lib/mirage/mirage_key.mli
- lib_runtime/functoria/functoria_runtime.mli
To test with: https://github.com/mirage/mirage-skeleton/pull/353
/cc @hannesm
> Prepare for git-mirage.v3.13.0 release and update devices

- functoria-runtime.opam
- functoria.opam
- test/functoria/e2e/help.t
- test/functoria/errors/run.t
- test/functoria/help/build.t
- test/functoria/help/clean.t
- test/functoria/help/configure-o.t
- test/functoria/help/configure.t
- test/functoria/help/describe.t
- test/functoria/help/query.t
- test/functoria/lib/run.t
- test/functoria/tool/run.t
- test/mirage/help/build.t
- test/mirage/help/clean.t
- test/mirage/help/configure-o.t
- test/mirage/help/configure.t
- test/mirage/help/describe.t
- test/mirage/help/query.t
as seen in the diff, this fixes #1220
> upgrade tests to cmdliner 1.2.0

- lib/functoria/makefile.ml
- test/functoria/query/run.t
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
> use the .opam.locked file for installing the switch dependencies

- .git-blame-ignore-revs
- .ocamlformat
- lib/functoria/install.mli
- lib/functoria/package.mli
- lib/functoria/tool.ml
- test/functoria/test_cli.ml
The aim of this commit is to gather feedback.
Changelog can be found here: https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md
> Upgrade to ocamlformat 0.26.0

- lib/mirage/mirage.ml
- lib/mirage/mirage_key.ml
- lib/mirage/mirage_key.mli
- test/mirage/describe/run.t
- test/mirage/query/run-dash_in_name.t
- test/mirage/query/run-hvt.t
- test/mirage/query/run.t
This provides a boot parameter specifying an amount of seconds to wait before starting up. This solves #1468.
> support for an initial delay of unikernels

- CHANGES.md
- lib/mirage/target/solo5.ml
- test/mirage/query/run-hvt.t
Authored-by: @hannesm hannes@mehnert.org
> allow solo5 0.8 line (works fine with the current set of things)

- CHANGES.md
- lib/functoria/impl.ml
- lib/mirage/impl/mirage_impl_git.ml
- lib/mirage/mirage.ml
- lib_runtime/mirage/mirage_runtime.ml
- test/mirage/query/config_noop.ml
- test/mirage/query/dune
- test/mirage/query/run-noop.t
//cc @samoht I went through the 4.4 branch and manually reconstructed the patches relevant for the main branch.
> 4.4 for main

- lib/mirage/impl/mirage_impl_arpv4.ml
- lib/mirage/impl/mirage_impl_block.ml
- lib/mirage/impl/mirage_impl_conduit.ml
- lib/mirage/impl/mirage_impl_dns.ml
- lib/mirage/impl/mirage_impl_ethernet.ml
- lib/mirage/impl/mirage_impl_git.ml
- lib/mirage/impl/mirage_impl_happy_eyeballs.ml
- lib/mirage/impl/mirage_impl_http.ml
- lib/mirage/impl/mirage_impl_icmp.ml
- lib/mirage/impl/mirage_impl_ip.ml
- lib/mirage/impl/mirage_impl_mimic.ml
- lib/mirage/impl/mirage_impl_misc.ml
- lib/mirage/impl/mirage_impl_misc.mli
- lib/mirage/impl/mirage_impl_reporter.ml
- lib/mirage/impl/mirage_impl_resolver.ml
- lib/mirage/impl/mirage_impl_stack.ml
- lib/mirage/impl/mirage_impl_syslog.ml
- lib/mirage/impl/mirage_impl_tcp.ml
- lib/mirage/impl/mirage_impl_udp.ml
- test/mirage/random-unix/main.ml.expected
- test/mirage/random-xen/main.ml.expected
> cleanups: small internal cleanups in mirage/impl

- CHANGES.md
- lib/functoria/DSL.ml
- lib/functoria/DSL.mli
- lib/mirage/mirage.mli
Extracted from #1493 
To be tested with https://github.com/mirage/mirage-skeleton/pull/386
> Remove DSL.foreign

- lib/functoria/DSL.mli
> add more documentation

- lib/devices/runtime_arg.ml
- lib/devices/runtime_arg.mli
- lib/functoria/DSL.ml
- lib/functoria/DSL.mli
- lib/functoria/runtime_arg.ml
- lib/functoria/runtime_arg.mli
- test/mirage/random/run.t
> Simplify Runtime_args.create

- lib/functoria/engine.ml
- test/functoria/e2e/errors.t
- test/functoria/e2e/errors/in_device/unikernel.ml
- test/functoria/e2e/errors/in_functor_not_enough/unikernel.ml
- test/functoria/e2e/errors/in_functor_too_many/unikernel.ml
- test/mirage/random/run.t
Fix #1528
Note: this is completely untested - I've just modified that number to match the description of the issue, so review/tests are very welcome 😅
> internal: Fix off-by-one locations in mirage/main.ml

- README.md
- lib/devices/dns.ml
- lib/devices/dns.mli
- lib/devices/happy_eyeballs.ml
- lib/devices/happy_eyeballs.mli
- lib/devices/mimic.ml
- lib/mirage.ml
- lib/mirage.mli
use with https://github.com/mirage/mirage-skeleton/pull/398
> Reverse the dependency between happy-eyeballs and dns-client

- lib/devices/ip.ml
- lib/devices/qubesdb.ml
for https://github.com/ocaml/opam-repository/pull/26350
> allow mirage-qubes 0.11 series

- lib_runtime/functoria/functoria_runtime.ml
- lib_runtime/functoria/functoria_runtime.mli
For context see https://github.com/mirage/mirage/pull/1574#issuecomment-2396431494
> Remove unused arg

- lib/mirage.mli
> update docs after the key / runtime_arg split

- lib/devices/ip.ml
The issue is if we define optional runtime arguments that the semantics are really unclear. I prefer to ensure (as it was in all users) that there's always an `--ipv4` boot parameter present.
The disturbance of `no_init` / `ipv4_only` / `ipv6_only` is still around. I've not enough head space to sort this through right now.
I plan adjust dns, git, happy_eyeballs in the same fashion and then cut a release.
> ip: no more optional runtime arguments

- lib/devices/dns.ml
- lib/devices/dns.mli
- lib/devices/git.ml
- lib/devices/git.mli
- lib/devices/happy_eyeballs.ml
- lib/devices/happy_eyeballs.mli
- lib/devices/ip.ml
- lib/devices/ip.mli
- lib/devices/misc.ml
- lib/devices/misc.mli
- lib/devices/network.ml
- lib/devices/runtime_arg.ml
- lib/devices/runtime_arg.mli
- lib/devices/stack.ml
- lib/devices/stack.mli
- lib/mirage.ml
- lib/mirage.mli
- lib_runtime/mirage_runtime_network.ml
- lib_runtime/mirage_runtime_network.mli
- test/mirage/random/run.t
works with https://github.com/mirage/mirage-skeleton/pull/403
> keys for DNS/HE/GIT devices

- lib/devices/target.ml
- test/mirage/query/run-hvt.t
this is for OCaml 5 support. //cc @shym @palainp @dinosaure
> allow ocaml-solo5 1.x series
