mirage/mirage

lib/mirage_misc.ml
When not redirecting output, don't try to read the log file on error.
Error was:
mirage: internal error, uncaught exception:
Sys_error("log: No such file or directory")
(is-mirage-broken is suffering from this: https://github.com/mirage/is-mirage-broken/blob/2cc7c6f691f84fb47144d5d049d2d1ace5c38e41/logs/mirage-www-ubuntu-14.04-4.01.0)
=> Fix missing log error

types/V1.mli
Closes #343.
Note: io-page 1.0.0 uses this for its unit-tests and may need a constraint added. 1.3.0 and later don't need it. Don't know what 1.1 and 1.2 are doing.
=> [RFC] Remove unused IO_PAGE module type

CHANGES, lib/mirage.ml
Classic mode makes it hard to see warnings among the verbose output. If some users want this, I think it would be better to make it a general ocamlbuild configuration setting rather than special-casing it for Mirage.
=> [RFC] Don't put '-classic-display' in the generated Makefiles

types/V1.mli
This allows for generic handling of errors without losing detail. For example, a user of a FLOW can use this to log errors. Before, the user would need to know the specific implementation of FLOW
being used.
This is required for TLS support in Conduit. It requires patches to console, vchan and tcpip to be applied first to add the extra method.
Longer term, we may want to add this function to `DEVICE` too.
=> Added error_message function to FLOW

types/V1.mli
When a module is functorised over a DEVICE it should only have the
ability to *use* devices it is given, not to connect to new ones.
This change also lets us get rid of the 'id' function from DEVICE.
The 'id' and 'error' types are still present to avoid breaking
existing code that uses 'with id = ...', but can be removed later.
This depends on some other patches being applied first:
And probably some other things...
=> [Tracking] Remove DEVICE.connect

lib/mirage.ml, lib/mirage.mli
In a `config.ml` one can use
- `default_entropy`: this is documented as "Pick the strongest entropy source available.". On Xen the only strong source we currently have is via `xentropyd`, although this could change with [mirage/mirage-entropy#9]
- `weak_entropy`: using this means that we will accept bad entropy, typically for dev/test/experimentation
Note that the Unix entropy source has been defunctorised while the Xen source needs to be functorised.
=> Support the 2 Xen entropy sources

CHANGES, lib/main.ml, lib/mirage.ml, lib/mirage.mli
This needs a companion PR in `mirage-www` and `mirage-skeletons` to remove any occurrences of `mirage run` in the docs and Makefiles.
=> Remove the `mirage run` command

CHANGES, lib/mirage.ml, lib/mirage.mli
Notes:
* Entropy is now initialised automatically, since we don't want to expose the application to this. Is this the correct way to do it?
* Conduit now *requires* a TLS implementation. Should this be optional?
* You can't configure an https web server directly because there's no way to pass in the configuration. Instead, your unikernel needs to take a conduit argument, load the certificate itself, and create the web-server from that.
* This depends on https://github.com/mirage/ocaml-conduit/pull/37
=> [RFC] Add TLS support in Conduit

lib/mirage.ml, lib/mirage.mli
This also support the VCHAN support from the mirage tool (it is still supported by conduit, though). I'm not sure it was working properly as we don't have example of its use in mirage-skeleton -- should be trivial to re-add if needed.
The main user-facing change is than now the conduit configuration for HTTP is given in `unikernel.ml` instead of `config.ml`: this is needed because you don't want `mirage` to depend on `tls` to provide the server-side configuration. Now the tool builds a callback which takes the http callback + the conduit server configuration which can then be used by the user code. An update to `mirage-skeleton` is following.
=> Changes to support the latest conduit+tls changes

lib/mirage.ml
This is minor, but `mirage build` says "Compiling for target: Unix" after configuring for Xen:
```
$ mirage configure --xen
Mirage      Using scanned config file: config.ml
Mirage      Compiling for target: Xen
...
$ mirage build
Mirage      Using scanned config file: config.ml
Mirage      Compiling for target: Unix
...
```
I thought the build had switched targets, but it's just `Mirage.load` printing the unset/default value of `Mirage.mode`.  It should only be printed during `configure`.
=> Misleading "Compiling for target" message from `mirage build`

lib/mirage.ml, lib/mirage.mli
The unikernel `config.ml` can use something like `archive_of_files ~dir:"./htdocs" ()` and then:
- `mirage configure` will generate a tar archive
- the .xl config file will have a completed `disk` section
- the .xe script will have a disk upload section
All the device numbering stuff is hidden from the user.
Example changes: [mirage/mirage-skeleton#99]
Requires tar-format.0.4.0: [ocaml/opam-repository#4503] (now merged)
Minimal wiki changes + support for "FS=archive": [mirage/mirage-www#372]
=> Support attaching files via a read-only tar-formatted BLOCK

lib/mirage.ml
Without this patch, unikernels that attempt to take a module of type `V1_LWT.TIME` and a `time impl` will fail at time of `make`, because mirage generates a `main.ml` with invalid syntax.
=> Provide noop configuration for default_time

CHANGES.md, lib/mirage.ml
The .xl file is unchanged and is mostly useful as an example of a working .xl file (except the network configuration which is still missing). For example you can build `mirage-skeleton/block` and immediately run it with the generated `block_test.xl`.
The .xl.in file contains everything needed for the VM to boot (again except the network configuration) but with `@VARIABLES@` which must be substituted by the sysadmin according to their preferences. For example every required `BLOCK` device is present as a `disk`, with the correct `vdev` (matching the `Block.connect` inside the kernel) but with a variable `@BLOCK:filename@` which should be replaced with the full path to the expected block device file on the host.
Ideally deployments will base themselves on the .xl.in file, substituting the …
=> Generate an .xl.in as well as an .xl file

lib/mirage.ml
Seem that it went unoticed in previous versions of Mirage. The new version seems to be more strict so it exposes that bug. That's good.
=> Fix OSX linking

lib/mirage.ml
So, As far as I understand:
- conduit doesn't actually need entropy unconditionally (it only needs it with tls).
- the entropy device's dependencies were wrong.
@hannesm, @samoht, please review. It seems to work in practice, but the dependency graph for those packages is far from being clear.
Fix https://github.com/mirage/mirage/issues/456
=> Add the correct dependencies for conduit/nocrypto.

lib/mirage.ml
Adds a "Build succeeded" message after the `ld` call in the Xen Makefile to avoid showing an error message as the last line for successful builds. See also issues https://github.com/mirage/mirage-skeleton/issues/106 and https://github.com/mirage/mirage/issues/258
=> Add "Build succeeded" message in Xen Makefile

lib/mirage.ml
Fixes https://github.com/mirage/mirage/issues/467.  @drup, could you confirm that this is the right fix?
=> Pass the original name, not the prefixed name, to 'connect'.

lib/mirage.ml
If meta_ipv4 is called in a context where it may be used in a
constructor (e.g. Some meta_ipv4), failing to parenthesize the call to Ipaddr.V4.of_string_exn
results in a compilation error on a currified constructor.
Parenthesizing hurts nothing, so just do it by default.
=> meta_ipv4 parenthesizes its output

lib/mirage.ml
This makes the .xe script robust against a VM already existing with the same
name.
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>
=> xe: Start VM using UUID, not name-label

types/V1.mli
This patch extends the description of `FLOW.close` to include discussion
of the flow state when one side has called `FLOW.close` and the other
has not.
Hopefully this is not actually a change in intended meaning, as the
mirage tcp/ip stack already behavies this way: `FLOW.close` is
implemented by sending a `FIN` to the peer which terminates only one
side of the full-duplex connection. When the peer finishes transmitting
all of its data -- at some arbitrary later date -- it will also send a `FIN`
to close the remainder of the connection.
`FLOW.close` means I will not call `write` again, so the peer can
receive `Eof` once it has read all pending/buffered data. This patch
clarifies that, after calling `close`, I can still call `read` to
read data being written by the other side, until the …
=> Clarify the meaning of `FLOW.close`

lib/mirage.ml
Causes upgrade trouble trying to remove the 'id' type.
=> Disable warning 34 on static files

lib/mirage.ml
Adding warn_error to the default tags for warnings that have been
enabled in the same step is a regression, since there has been no
inermediate period where this warnings could have been fixed.  This
change removes the warn_error tag from the default tags.
Fixes: #520
=> Remove warn_error from default tags

.travis.yml, lib/mirage.ml, types/V1.mli, types/V1_LWT.mli
Currently, ICMP functionality is implicitly provided by the modules implementing IPV4 and IPV6 module types.  Define a module type for ICMP to facilitate pulling this functionality out of IPV4/6 in order to make it more explicit and extensible.
=> Introduce a module type for ICMP and ICMPV4.

types/V1.mli
Per @talex5's suggestion, call it pp_error instead of pp_of_error .  Should be merged alongside https://github.com/mirage/mirage-tcpip/pull/197 .
=> ICMP: change pp_of_error to pp_error

.travis.yml, lib/mirage.ml
This is the default behaviour if you have a _tags or myocamlbuild.ml,
but not otherwise in case you're running from your home directory. In
our case, we know the current directory is a valid project and can
always have this on.
Avoids a long and misleading error that is otherwise printed after every
compilation failure telling the user to enable this.
Fixes #536.
=> Build with ocamlbuild -r

.travis-ci.sh, .travis.yml, types/V1.mli
Some transport layer protocols want to calculate a checksum over fields from the underlying network layer (the "pseudoheader").  Require modules to provide a `pseudoheader` function which assembles the correct pseudoheader given the parameters this should express.
Implementations of `pseudoheader` for IPv4 and IPv6 are included in a PR to `mirage-tcpip`.
=> Require "pseudoheaders" function for IP module types.

types/V1.mli
This standardises on the present tense and active voice (rather than e.g. the future tense). Most of the API was already like this, but it was inconsistent.
There's no implied semantic change in this PR (at least I hope not!)
This PR also starts a new section at the top called "General conventions" which calls out
1. errors which the application is supposed to handle (e.g. connection refused) are represented as error values
2. errors which the application is not supposed to handle (e.g. assertion failures) are represented as exceptions which are expected to abort the program with diagnostic data
3. operations which perform I/O return a `type +'a io` which allows the application to either wait for completion or let them run asynchronously.
=> Minor API docs updates: use the present tense and active voice

.travis-ci.sh, .travis.yml, lib/mirage.ml, lib/mirage.mli, types/V1.mli, types/V1_LWT.mli
Attendant changes in mirage-tcpip are required (see https://github.com/mirage/mirage-tcpip/pull/200 and the forthcoming PR building on it) along with changes in any `config.ml` which invoked an affected configuring function:
* `direct_stackv4_with_default_ipv4`
* `direct_stackv4_with_static_ipv4`
* `direct_stackv4_with_dhcp`
* `socket_stackv4`
* `generic_stackv4`
PRs for `mirage-skeleton` and `dns`, two prolific packages affected by these changes, will be submitted shortly.
=> don't supply console to stackv4

.travis-ci.sh, .travis.yml, README.md, lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli
See #461 for motivation, and https://github.com/mirage/functoria/pull/65 for the related upstream change.
This patch removes the following deprecated functions:
* invoking mirage configure --unix and mirage configure --xen to build for UNIX/Xen targets.  Instead, use mirage configure -t unix or -t xen.
* using add_to_opam_packages to install extra required packages not detected by the mirage front-end tool.  Instead, pass the same list to `register` in the ~packages named argument.
* similarly, using add_to_ocamlfind_libraries to link against extra libraries.  Instead, pass the same list to `register` in the ~libraries named argument.
=> Deprecate functions which require functoria base_context

.travis-ci.sh, .travis.yml, types/V1.mli
I got derailed while wanting to adapt the RANDOM module type with the TIME module type.
Its documentation:
```OCaml
val sleep: float -> unit io
(** [sleep nsec] Block the current thread for. {b FIXME:} remove float. *)
```
I propose to have: `val sleep : Int64 -> unit io`, the amount of nanoseconds (this is what we get out of the monotonic clock on [xen](https://github.com/mirage/mirage-platform/blob/ed19a1a318e944a7020239fa01c0b674b02cf471/bindings/clock_stubs.c#L39), and likely as well from Lwt_unix.sleep.  The range will be up to 9223372036854775807L nanoseconds (106751 days).
I've PRs for (compiles + test run with 4.03 on Unix (FreeBSD)):
- [mirage-platform 188](https://github.com/mirage/mirage-platform/pull/168) (mirage-xen and mirage-unix)
- [mirage-solo5 …
=> TIME: use an int64 for sleep

lib/mirage.ml
As spotted by @hannesm in #565, this is not required here and will be
pulled in from ocaml-freestanding pkg-config.
=> Remove extraneous solo5-kernel-ukvm from configure_makefile

lib/mirage.ml
Fixes solo5/solo5#70 (easier doing it here than the other way round) and
mirage/mirage-skeleton#178.
=> ukvm target: Correct use of "blk" for block module

lib/mirage.ml
This relatively innocuous change adds arguments like `-tags 'predicate(xen)'` to the `ocamlbuild` invocation in the `Makefile`. The set of tags is currently `[unix, xen, solo5]`, but this is open for discussion.
The motivation is my long standing frustration: one can do a variety of simple interactions with the system from the code written directly in a unikernel, but it's almost impossible to extract that code to a library.
One example is in the [simplest Mirage demo](https://github.com/mirage/mirage-skeleton/blob/079e37e1b46831e9816c84f19a491356856994e9/console/unikernel.ml#L10). This call is not available from code compiled separately. Of course, I can use a [different one](https://github.com/mirage/mirage/blob/9a52cca64e25feef35099ca2bfd8e4ad52b881ed/types/V1.mli#L76) for that …
=> Emit an ocamlfind predicate that matches the target

lib/mirage.ml
This change is needed to get `io-page` included in the set of packages against which a unikernel that includes a `crunch` filesystem builds.  The autogenerated `staticN.ml` requires `io-page`, but installing and running `crunch` itself doesn't, which is why the dependency isn't expressed in the `opam` file for the `crunch` package.
`get_extra_ld_flags` in `mirage.ml` will find `io-page` in the list when compiling for `-t xen` already, because `io-page` is a dependency of the `mirage-xen` package, so we always get it "for free" in that backend -- otherwise, the existing code wouldn't have ever worked.
=> Express io-page dependency of crunch in libraries and packages.

Dockerfile.doc
… and runs a webserver
```
docker build -t mirage-doc -f Dockerfile.doc .
docker run -d --name mirage-doc -p 8080:8080
```
Still experimental, dont merge quite yet (PR for autobuild purposes)
=> Add a Dockerfile that generates package documentation

lib/mirage.ml, lib/mirage.mli, types/V1.mli, types/V1_LWT.mli
this is only the interface change -- after discussion I'll adapt the mirage tool to do the magic.
- in contrast to common believe, there is no need for random to have blocking behaviour
- helper functions which generate *your favourite number representation here* between bounds will be done in a helper library (no need to convolute the interface with it)
- my current plan is to have two implementations: OCaml's `Random` and nocrypto's fortuna.  if anywhere in your dependency chain you have `nocrypto` already, that one is used as `default_random` (the [logic for this is already in the mirage tool](https://github.com/mirage/mirage/blob/074cb5fe080b23779bddeb24ddb59f24766fd5c0/lib/mirage.ml#L763-L781)).  you can always explicitly pass the [lagged-Fiobnacci …
=> [RFC] simplify random

types/V1.mli
It frequently happens that a KV_RO implementor can have failures other than `Unknown_key`.  Allow for a blanket `Failure` type to communicate these to the user.  Currently implementors tend to return `Unknown_key` for all underlying failure types, which is often erroneous and may lead the user to believe that some action on their part might make the problem go away.
Also, require implementors of KV_RO to include a `mem` function indicating whether the given key is present in the key-value store.
Fixes #147 .
Relevant PRs in other libraries:
A `mirage-skeleton` build in this universe can be seen at https://travis-ci.org/yomimono/mirage-skeleton/builds/164427007 .  To test for yourself, you can `opam remote add mirage-dev-kvro_mem https://github.com/yomimono/mirage-dev.git#mem-in-kvro` to …
=> Require a `mem` function in KV_RO; allow failures other than `Unknown_key`

lib/mirage.ml, types/V1.mli
two changes:
- `connect` does not return a result anymore (somehow this slipped through a rebase)
- a `generator` type in `RANDOM` interface, and use it in `generate`.  this makes the signature the same as Nocrypto.Rng, and thus interoperable.
=> Random fixes

types/V1.mli
Also, remove constraints and destructive replacements of `id` from
module types which include `DEVICE`.
=> finally remove `id` from DEVICE module type

types/V1.mli
Documentation claimed that `listen` and `input` would start asynchronous threads
and return immediately.  This is incorrect; implementations don't return
until `disconnect` has been called on the underlying interface.
=> correct comment on `listen` and `input` operation in NETWORK and ETHIF

lib/mirage.ml
Reverts mirage/mirage#623 /cc @hannesm.
Getting LD this way does not actually work, `export PKG_CONFIG_PATH` does not affect the environment used by `$(shell ...)`. Given that this breaks current master I'm going to revert this PR and work on a proper fix where `mirage` will call out to `pkg-config` itself.
=> Revert "reword missing ocaml-crunch slightly; use LD from pkg-config for virtio"

lib/mirage.ml
Rather than invoking pkg-config from within the generated Makefile,
invoke it directly at "configure" time.
Pros:
- This allows us to set variables like "LD" (see #623) sensibly.
- Generated Makefile contains the actual commands which will be run,
rather than call-outs to pkg-config whose output may change at build
time.
Cons:
- "mirage configure" needs to be re-run if dependent packages are
updated, to reflect any new pkg-config variables in the generated
Makefile.
@avsm @hannesm @yomimono Please review, taking into account the above pros/cons.
=> Invoke pkg-config directly when generating Makefile

lib/mirage.ml
this was merged and reverted (due to the LD changes)
=> reword missing ocaml-crunch slightly so that it points to the missing opam package

lib/mirage.ml
See https://github.com/mirage/mirage-dev/pull/175 . `solo5` is still `mirage-bootvar`, at least for the moment.
=> library for mirage-bootvar-xen is now mirage-bootvar-xen

lib/mirage.ml
Adjust the dep logic around `nc`.
This is consistent with
and should be merged after those.
=> Lesscrypto

lib/mirage.ml
... and *rename* it.
Words like `xen`, and especially `unix`, hog the single `ocamlfind` predicate namespace. As this could become part of a long-lived API, I changed them to something more descriptive.
=> Pull out the backend predicate

Dockerfile.doc
requires mirage/mirage-dev#179
=> docs: build mirage-entropy instead of mirage-entropy-xen

lib/mirage.ml
no use for those when using solo5 afaik
=> generate .xl, .xl.in, .xe, and _libvirt.xml only if we're targeting xen

.travis-ci.sh, .travis.yml, lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli, types/V1.mli, types/V1_LWT.mli
TL;DR : make DHCP configuration of ipv4 a first-class citizen; remove `mode`, many type signature changes.
Details:
* Use charrua-client's Dhcp_ipv4 module to configure an ipv4 impl with dhcp.
Disambiguate between the two ipv4 modules by calling the static one
ipv4_keyed_conf (because it's configured through the key system) instead
of ipv4_conf .  generic_stack will now choose between a keyed
configuration and a DHCP-based one depending on the value of the `dhcp`
key.
* change the "network" key, defining which interface a V1_LWT.NETIF
should attempt to attach to, to "interface".
* changing V1_LWT.IPV4's prefix type to Ipaddr.V4.Prefix.t,
addressing a longstanding FIXME.  Ipaddr.V4.Prefix.t defines a
network, not just a netmask, so change this name and provide the
expected converters.
* …
=> improvements to ipv4 configuration

lib/mirage.ml
Without this change, attempting to build stacks with `--net=socket` generates a broken `main.ml`.
=> add missing } to `connect` code generation for socket stack

lib/mirage.ml
It would of course be nicer to have tracing on solo5, but we don't.
Fixes #650 .
=> fail if the user tries to build tracing with solo5 target

lib/mirage.ml
Thanks to @mato investigation [in mirage-solo5](https://github.com/mirage/mirage-solo5/pull/15), pc files should be installed into `share/pkgconfig` rather than `lib/pkgconfig` (which is not possible with `.install` files, but only with shell scripts and hacks).
The `lib/pkgconfig` path was hardcoded by several opam packages:
The xen part (minios-xen or mirage-xen-minios) somewhat breaks, and I cannot get much debug information from travis... someone with a test setup please test and fix it, should be straightforward.
A mirage-dev travis run with working unix + solo5 builds is available at https://github.com/mirage/mirage-dev/pull/209
Update: none of the PRs needs to be merged, ocb-stubblr and this PR here now use both `share/pkgconfig` and `lib/pkgconfig` as search PATH.
=> Use both lib/ and share/ for PKG_CONFIG_PATH

Dockerfile.doc
This gives us a more modern depext base (e.g. for gsl).  I'll
eventually make it work on Debian Stable and Alpine, but there
are a few blocking packages there.
=> docs: change the base to an Ubuntu 16.04 build

lib/mirage.ml
this fixes the `mirage configure` step you see failing in Travis.  sorry again for this breakage and the mirage-console-* breakages...
=> need a String.trim after `opam config var prefix`

.travis-ci.sh, .travis.yml
In the mainline `.travis-docker.sh`, the `MODE` environment variable isn't passed to the container which runs the tests, resulting in `make` in `mirage-skeleton` defaulting to `unix`.  (See https://github.com/ocaml/ocaml-ci-scripts/issues/136 .)  Use a branch which passes `MODE` to the container.
=> pass MODE to container when testing

.travis-ci.sh
`mirage-types` tests still fail, but it's a real failure rather than a spurious one (no `tls.mirage`).
=> restore opam depext to travis-ci.sh

lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli
This PR adds an additional mode for Qubes.  If invoked with `-t qubes`, `mirage` will include in the generated `main.ml` some invocations of the libraries in [mirage-qubes](https://github.com/talex5/mirage-qubes) necessary to boot in that environment.
Much like the `MacOSX` target has a lot in common with `Unix`, `Qubes` is mostly the same as `Xen` with the exception of these extra invocations.
=> add Qubes target

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli
I looked through a7cff94d354af6c0824f02a34718000369fd09d9 -- looks good otherwise (I couldn't find any other unintended merges)
=> re-apply 077d852ef14cc5e00620a22a16b75f1152761f22, lost during qubes merge

Dockerfile.doc
rename mirage-clock-xen to account for mirage/mirage#684
=> docs: add all the freestanding packages

lib_runtime/mirage_pp.ml, lib_runtime/mirage_pp.mli, types/V1.mli
Confession: I'm not very happy with this PR, but it and the corresponding upstream universe at https://github.com/yomimono/mirage-dev/tree/higherlevel-error are probably the best I'm going to do without more outside input.  Things it does:
* continues the pattern set by @hannesm in the earlier work adding result types to `write` functions in the `NETWORK` module type for `ETHERNET`, `IP`, `ARP`, `ICMP`, `UDP`, and `TCP`.  `TCP.create_connection` also now returns a result type.  As in the earlier PR, error types are defined in `V1` and printers in `Mirage_pp`.
* refactors the `FLOW` module type to use result types for both `read` and `write`.
Things it doesn't do:
* anything with the storage stack
* provide nice combinators
* anything with `input` types
PRs for users of these interfaces: …
=> add result types for FLOW & most `write`-like functions in networking components

lib_runtime/mirage_pp.mli
While we do not normally support OCaml 4.02 in Mirage, this is
a fairly easy change to make to maintain compilation support
vi using `Result.result` instead of `result`.
=> Restore 4.02 compilation of the runtime library

lib/mirage.ml
This hack was needed at some time on FreeBSD, but is no longer -- cleaning up
This complements https://github.com/Solo5/solo5/pull/123 waiting for @mato
=> Do not use LD from pkg-config, but just the system one

.travis.yml, types/V1.mli, types/V1_LWT.mli
Changes:
- remove `read_stream` and `io_stream` as Lwt_stream is difficult to
combine with error handling
- remove `read_until` and only expose the line handling functions.
I'm also considering moving the line-handling functions into a
separate signature since most consumers of CHANNEL only want the
buffering logic.
- no more exceptions, just use `result` and propagate `FLOW.error`
in return values.
Dependent PRs:
=> [WIP] Refactor CHANNEL types to be exception-less and use `result`

Dockerfile.doc
They are not building at the moment, fixes in progress for both and
will be reinserted when building
=> doc: temporarily disable arp and mirage-block-ramdisk from docs build

lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli
Fixes #649 .  I believe this behavior is nicer:
```
4.04.0🐫  ((detached from origin/mirage-dev)) mirageos:~/mirage-skeleton/network$ mirage clean && mirage configure --net=direct -t unix
=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[mirage-types] /home/user/mirage#ipv4-network-one-key updated
[mirage-types-lwt] /home/user/mirage#ipv4-network-one-key updated
[NOTE] Package functoria-runtime is already installed (current version is dev~mirage).
[NOTE] Package lwt is already installed (current version is 2.6.0).
[NOTE] Package mirage-clock-unix is already installed (current version is dev~mirage).
[NOTE] Package mirage-console-unix is already installed (current version is dev~mirage).
[NOTE] Package mirage-logs is already installed (current version is …
```
=> specify ipv4/netmask as one parameter in the "network" key.

lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli
As requested in https://github.com/mirage/mirage/pull/707 . There was a converter named `ipv4` for plain addresses (used in interpreting `gateway`), so I've renamed that to avoid confusion.
=> rename ipv4 to ipv4_address, ipv4_network to ipv4

lib/mirage.ml, lib/mirage.mli
Fixes #644 .
Does not fix #645.
Needs changes in unikernels that previously used `tap0`; there's a [matching PR for mirage-skeleton](https://github.com/mirage/mirage-skeleton/pull/203).  To see a consistent universe, check [this fork of mirage-dev](https://github.com/yomimono/mirage-dev/tree/default-network).  Its passing tests are visible [here](https://travis-ci.org/yomimono/mirage-dev/builds/180195689).
=> replace tap0 with default_network

lib/mirage.ml
Followup to #715. Solo5 does not currently care about the string passed
to Netif, so just use "0" for all non-Unix targets.
=> Make "0" the default network interface on non-Unix targets

lib/mirage.ml
Fixes #596.
@avsm I've deliberately not used `--update` in the call to `depext`; I don't think we did that before and it can modify the user's package manager state which IMO is not good for default behaviour.
=> Install depexts for unikernel during make depend

lib_runtime/mirage_pp.ml, lib_runtime/mirage_pp.mli, types/V1.mli
Include an ARP error variant; it can be returned as an error result from `query` in module type `ARP`.  (For reals this time.)
Requires changes to `tcpip` which you can see at https://github.com/mirage/mirage-tcpip/pull/269 .
To see passing tests, check out the results for the `mirage-dev` universe including this branch and the matching `tcpip` one: https://travis-ci.org/yomimono/mirage-dev/builds/179917304
=> Arp result types

lib/mirage.ml
Without these changes, create_ipv6 generates code that contains a stray
@ and also fails to pass the required `clock` parameter to Ipv6.connect .
=> fix incorrect connect string for create_ipv6

lib/mirage.ml
If this is done in `configure`, we haven't yet had a chance to generate the list of dependencies and install them.  The user (especially if they're a CI system) might not have had a chance to install `fat-filesystem` yet.
=> move fat generation to build phase

lib/mirage.ml
Attempting to use some of the filenames generated by slapping `dir` and `regexp` together isn't going to go too well.
Also, `fpath`'s `/` threw an exception when `dir` was `../other-subdir` in the previous implementation.  `Fpath.append` on the result of `Fpath.v dir` works fine.
=> ocamlify names used in fat block construction & reference

lib_runtime/mirage_pp.ml, lib_runtime/mirage_pp.mli, types/V1.mli
For a consistent (with the exception of `fat-filesystem`) universe, see https://github.com/yomimono/mirage-dev/tree/fs-errors .  To see a passing test, visit https://travis-ci.org/yomimono/mirage-dev/builds/179518397 .
A number of other PRs will need to be merged once this is:
=> result-y FS, KV_RO, and BLOCK module types

pkg/META.mirage-runtime
I guess it's added by the mirage tool at some point, but it's better to keep track of it there.
=> mirage-runtime depends on mirage-types

types/V1.mli
`format` is similar to `connect` which we removed previously from the common interface: it is likely to be implementation-specific (e.g. number of inodes, number of superblocks etc etc)
Furthermore it seems strange to have to acquire a `FS.t` handle in order to be able to format a filesystem. This requires that implementations track whether the `FS.t` is formatted or not (e.g. with a Some or None) and then all operations may return `Format_unknown` (which they currently can't). Removing `format` and `Format_error` fixes this problem.
With this change, `Fs.error` is a proper subset of `Fs.write_error`.
=> FS: remove `format` and `Format_unknown`

lib/mirage.ml, mirage-types-lwt.opam, mirage-types.opam, pkg/META.mirage-types, pkg/META.mirage-types-lwt, pkg/pkg.ml
This PR solves #670 by moving `mirage-types.lwt` into the `mirage-types-lwt` package, thus we do not have any depopts anymore.  A successful build of mirage-skeleton is available at: https://travis-ci.org/hannesm/mirage-dev/builds/183748895
It affects some packages:
=> move mirage-types.lwt to mirage-types-lwt

Dockerfile.doc
ocamldoc is now available from the /ocamldoc sub-url but we have
cross-referencing by default
=> doc: swap the ocamldoc/odoc default so that odoc is default

lib/mirage.ml
- remove all raise from `method package`
- in case a device is not suitable for the target, `configure` emits an error
- don't Log.err _and_ R.error_msg, only use the latter
- unify connect error message
- use Fmt.strf all over instead of partially Printf.a/sprintf
- crunch has a build-dep on crunch, no need to verify manually that crunch is
around during build time
- when matching target, don't use wildcards
- massage code to 80 columns
=> mainly cosmetics

Dockerfile.doc
to get a building docs tree again
=> doc: temporarily disable qcow-format and vhd-format

lib/mirage.ml
Without this fix, `mirage configure -t qubes` generates a `main.ml` that does not compile.
=> fixes newline in bootvar connect

.merlin, .travis.yml, Makefile, _tags, lib_runtime/mirage_pp.ml, lib_runtime/mirage_pp.mli, mirage-runtime.opam, mirage-types-lwt.opam, mirage-types.opam, pkg/META.mirage-types, pkg/META.mirage-types-lwt, types/V1.mli, types/V1_LWT.mli
Following the discussions we had with @talex5, @yallop and @hannesm last week, I implemented the new error scheme using private rows. After finding [2](https://caml.inria.fr/mantis/view.php?id=7437) [bugs](https://caml.inria.fr/mantis/view.php?id=7438) in the compiler, I finally managed to get something working. Here is the full set of patches:
- mirage-device (DEVICE): [GitHub - mirage/mirage-device: Mirage device](https://github.com/mirage/mirage-device)
- mirage-time (TIME):  [GitHub - mirage/mirage-time: Time signatures for MirageOS](https://github.com/mirage/mirage-time)
- mirage-random (RANDOM) : [GitHub - mirage/mirage-random: Random-related devices for MirageOS](https://github.com/mirage/mirage-random)
- mirage-console (CONSOLE) + errors: [Update the new error scheme in …
=> Refactors errors and split signatures into their own opam packages

lib/mirage.ml
Ideally, `tls-mirage` will be a thing, but that's fine for now on.
/cc @hannesm
=> Fix the dependencies of the tls device

.merlin, _tags, mirage-runtime.opam, mirage-types-lwt.opam, mirage-types.opam, mirage.opam, pkg/META.mirage, pkg/META.mirage-runtime, pkg/META.mirage-types, pkg/META.mirage-types-lwt, types/mirage_types.mli, types/mirage_types_lwt.mli
- adjust merlin
- add mirage-stack{-lwt} mirage-protocols{-lwt} to META of mirage-types{-lwt}
- export Mirage_types_lwt.{PCLOCK, MCLOCK} (provided by mirage-clock-lwt)
imho straightforward @yomimono
=> mirage-types-lwt: minor fixes

Dockerfile.doc, mirage-runtime.opam, mirage.opam
(see https://github.com/sg2342/mirage-block-ccm/pull/21)
=> mirage-block-ccm works with new MirageOS

lib/mirage.ml, lib/mirage.mli
As of https://github.com/mirage/ocaml-fat/commit/45b521b4d0254cbf5c1bbcb573fa2af79f4805d7 , ocaml-fat no longer expects to take an Io_page module argument.  Don't try to pass it one.
=> don't pass io-page module to ocaml-fat FS.make

lib/mirage.ml
`dns` provides `Dns_resolver_mirage.Make` , not `Resolver_mirage.Make_with_stack` and doesn't look like the right fit for the generated code.
=> fix resolver depends (uses conduit, not dns)

README.md
Because functoria 2.0.0 requires 4.03.0 or later
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
=> readme: Bump minimum OCaml version to 4.03.0

Dockerfile.doc
They will be restored once released; as they now must be in stable
opam for this to work since #803
=> doc: Temporarily disable some unreleased packages

lib/mirage.ml
`-t qubes` is useful to run generic unikernels on Qubes, but for Qubes-specific unikernels we need to use the Xen target so that we can control the agents directly.
See e.g. https://github.com/talex5/qubes-mirage-skeleton/pull/2
=> Allow qubesdb to be used under Xen

Dockerfile.doc
This leads to an epic conflict with uuseg, git, cmdliner and the
world explodes.  I just want to rebuild docs.mirage.io and then
re-add the packages in a cmdliner 1.0 world, so disabling git-unix
for now from the docs list.
=> docs: also prune git-unix for now until we can carefully re-add

lib/mirage.ml
OCaml (since 4.03.0) attempts to colorise warnings and errors (in a "auto" mode
by default, which checks whether stdout is a tty).  ocamlbuild does not execute
ocaml in a tty, this is why by default there is no color.
An upstream fix to consider the environment variable OCAML_COLOR in case no
"-color" command line flag was provided is proposed, and may be included in
4.05.0.  In the meantime, revert to no colored output (as in Mirage <3.0.0).
Fixes #797 (and @haesbaert mentioned the same in some emacs script https://github.com/mirage/mirage/issues/761#issuecomment-280501942)
=> don't add "-color always" to ocamlbuild invocation, since it breaks some scripts

lib/mirage.ml
we are now able to express version constraints for unikernels via `package` -- use this to constrain mirage3 configured unikernels to mirage3 packages
=> mirage: put some lower bounds on packages

lib/mirage.ml
In not-strictly-opam environments (e.g. opam2nix), `opam config var prefix` may fail or not be where dependencies actually are. This patch allows falling back to `pkg-config` libraries in the system's `$PKG_CONFIG_PATH`, if set.
=> fallback to system $PKG_CONFIG_PATH

Dockerfile.doc
Needed for mtime.1.0 support.
The upstream issue for odig is https://github.com/dbuenzli/odig/pull/27
=> docs: pin odig to a building branch to refresh our docs

lib/mirage.ml
This uses separate opam packages for Xen and Unix tracing.
/cc @djs55
=> Update for mirage-profile 0.8

lib/mirage.ml
Previously the correct stubs were found because `io-page` was in the
dependency list and everything was in the same `META` file with global
`xen_linkopts`. [mirage/io-page#46] splits `io-page` into 3 packages
and hence 3 distinct `META` files. Therefore we must depend explicitly
on `io-page-xen` to discover the `xen_linkopts`. This patch also adds
a dependency on `io-page-unix` to the `Unix` target for symmetry, although
there is no `xen_linkopts`: the OCaml compiler figures that out for itself.
=> Automatically require io-page-{xen,unix} on Xen and Unix

lib/mirage.ml
Required by [mirage/mirage-qubes#14]
=> qubes: use the new mirage-qubes-ipv4 package

CHANGES.md, lib/mirage.ml
Neither of these backends should need or can use the Unix stub.
I built these using
```
opam init git://github.com/djs55/opam-repository#io-page
opam pin mirage .
git clone git://github.com/mirage/mirage-skeleton
cd mirage-skeleton
make clean && make MODE=xen
make clean && make MODE=unix
make clean && make MODE=virtio
make clean && make MODE=ukvm
```
(I notice the CI only does `xen` and `unix`)
```
=> Remove io-page-unix from Ukvm and Virtio

Dockerfile.doc
pinning cstruct ensures that we can cull packages that are
lagging behind the dependency cone. This is just tlstunnel
for the moment.
=> doc updates: remove odig pin, trim package list, pin cstruct

Dockerfile.doc
- dev version of magic-mime should detect markdown files
- ocamldoc is really slow and unreliable now, not worth building by default
- 4.04.1 works for everything, so shift to it!
@dbuenzli i can reinstate ocamldoc if you have a use for it, but its adding quite a bit of build time and causing timeouts, so removing it in the short term
=> docs: shift to 4.04.1 build, disable ocamldoc and use new mime db

Dockerfile.doc
- tyxml-ppx: can move to a web oriented one
- topkg
- opam-lib: both pulled in as deps
=> docs: add camlzip, remove some extraneous ones

lib/mirage.ml
This is more reliable.  The update won't be triggered if all packages are
installed.
Alternative to #840.
=> Call depext with the --update flag in make depend

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli
ukvm has a `gdb` module that starts a GDB server so debuggers can attach to it. Linking the `gdb` module is defined in `Makefile.ukvm` which is generated by mirage for every `ukvm` unikernel. This change adds a mirage `--gdb` flag that defines whether to add the `gdb` module to `Makefile.ukvm`. Additionally, this change also moves the generation of `Makefile.ukvm` to the mirage configure phase.
Here is the proposed flag, for the ukvm target:
```
$ mirage configure --gdb -t ukvm
$
```
and this for all others (just a warning):
```
$ mirage configure --gdb -t unix
mirage: [WARNING] --gdb not supported on this target.
$
```
You might have to pin the lastest solo5.
@mato
=> Adding --gdb argument for ukvm

.travis-ci.sh, .travis.yml, lib/mirage.ml
This won't work without a bunch of pins until the latest charrua packages are released (see https://github.com/mirage/charrua-core/pull/70 for the preparation PR).  If you want to try it out, pin `charrua-core`, `charrua-client`, `charrua-client-lwt`, and `charrua-client-mirage` to that branch.
Lots of stuff is still broken but this is a start.
=> build fixes for --dhcp=true, networking with -t unix, and conduit

lib/mirage_key.ml
I don't think anyone is either still using such an arcane system, neither is anyone interested in supporting it.  Or am I wrong here?
=> remove MacOSX < yosemite support

.travis-ci.sh, .travis.yml, CHANGES.md
This is a point release needed by rename of `mirage-http` to `cohttp-mirage` in [mirage/ocaml-cohttp#572] (due to be released in `cohttp.1.0.0` and `cohttp-mirage.3.0.0`)
=> Prepare to release 3.0.6

mirage-runtime.opam, mirage-types.opam, mirage.opam
This fixes the output of `make opam-pkg`, since `topkg` assumes the
download URL is based on the `homepage`.
See for example [ocaml/opam-repository#10843]
Note that mirage-types-lwt already used github.com/mirage/mirage
(and so was inconsistent with the rest). Now all are consistent.
=> opam: use https://github.com/mirage/mirage as the homepage

lib/mirage.ml
The logic for the `Xen` and `Qubes` cases is redundant with logic in `mirage-block-xen`'s connect module: see https://github.com/mirage/mirage-block-xen/blob/master/lib/blkfront.ml#L488 .
=> allow access to xen block devices other than the first

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli
This change adds the Muen platform to the mirage tool so it can be chosen as a target for MirageOS unikernels. It has been tested and is actually already in use for several weeks to build and run the Muen project website (see also description [here](https://muen.sk/articles.html)).
This is the remaining puzzle piece to fully upstream Muen support for MirageOS, see also Solo5/solo5#194.
Note: the necessary adaptations on the Muen side have been merged and released as part of [v0.9](https://groups.google.com/forum/#!topic/muen-dev/FPL9sc4yaBE).
=> Add new Solo5-based platform `Muen

lib/mirage.ml
Add maintainer, authors, homepage, bug-reports fields with a content of "dummy" to supress opam lint warnings during "make depend".
=> Supress lint warnings from generated opam file

lib/mirage.ml, lib/mirage.mli, lib/mirage_key.ml, lib/mirage_key.mli
This patch reverts #874 to fix #878 .  It also tries to solve the original problem #874 addressed by giving the user handles to directly specify a XenStore ID for block devices.  This can be called directly from `config.ml` with `block_of_xenstore_id` or invoked via the configuration language with `generic_block` in `config.ml` and `--block=xenstore`.  Attempting to use `--block=xenstore` with a Unix-y or Solo5-y target will result in a configure-time error.
/cc @cfcs .
=> allow directly specifying xenstore ids for block devices

mirage.opam
see https://github.com/ocaml/dune/issues/567 , which explains the issue
with jbuilder 1.0+beta18 in more detail.  This broke our ability to use cohttp
(at least, maybe more), and it's (IMO) easiest just to conflict with it.
=> conflict with jbuilder 1.0+beta18

lib/mirage.ml
Before, for targets which caused us to build an `.xl`, we would always generate two (!) disk configurations (one for `tar` and one for `fat`) per call to `generic_kv_ro`, regardless of which implementation was actually chosen (including `crunch`).  With this patch, we only include block configuration relevant to the final config.
By way of illustration, here's the `https.xl` generated by `mirage configure -t xen` in the `static_website_tls` directory of `mirage-skeleton`(with https://github.com/mirage/mirage-skeleton/pull/255 applied), regardless of which `--kv_ro` values are passed:
```
4.05.0🐫  (choose-kvros-separately) 18.25 ocamldev:~/mirage-skeleton/applications/static_website_tls$ make clean && mirage configure -t xen --data-kv_ro=fat --certs-kv_ro=crunch && cat https.xl
mirage …
```
=> Reduce extraneous block config generation

lib/mirage.ml
Otherwise `make depend` when using opam version 2 has some surprising behavior.
/cc @mato
=> use a path pin when making depends

lib/mirage.ml
In Qubes, the hypervisor has its own logic and rules for configuring
guests which needs to be configured out-of-band, so these files aren't
useful.
=> don't make xen config documents for target qubes

lib/mirage.ml
this is needed again for OpenBSD support in solo5 (since OpenBSD's `ld` is an ancient `GNU ld`, which doesn't work with the solo5 linker script -- but their `ld.lld` (from clang/llvm) does..
//cc @adamsteen @mato
this basically reverts e0aba4dc2dac7f180517b7b129e8e890617a8e15 -- but since `ld` is no longer called via Makefile, but rather from OCaml code, it needs some adjustments.
the failure semantics (if `pkg-config` returns an error) is atm to log (on the warning channel) and call out to `ld`.
=> respect ld from pkg-config

lib/mirage.ml
As per this [discussion](https://discuss.ocaml.org/t/mirageos-orchestration/1989/4), an example libvirt.xml file should be emitted when configuring virtio unikernels (as they are with xen).
I've tested the example output including clock, network and console devices. The only `virtio` feature that isn't demonstrated is `block` devices which don't appear to be supported by mirage for `virtio`.
=> Add libvirt.xml for virtio configuration target

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli
Now that Solo5 0.3.0 has been released, and the Mirage/Solo5 packages are all published on opam.ocaml.org, this can be merged into mirage `master`.
User-visible changes:
- Add new Solo5-based platform `Muen (#887) 
- respect ld from pkg-config (#898) 
I've reviewed both of these again and there are no backward incompatibilities here, obviously #887 will only work with the Solo5 0.3.0 packages.
=> Merge dev-solo5 branch into master

lib/mirage_key.ml
This changes nothing. In particular, this doesn't fix the failure in 4.07 since the current definition in functoria is exactly the same.
However, it delegates the definition to functoria which means we can fix everything there.
=> Use the exposed signature in functoria for Key modules.

CHANGES.md, lib/mirage.ml, mirage-runtime.opam, mirage-types-lwt.opam, mirage-types.opam, mirage.opam
we need #912 for 4.07.0 support, thus I've updated CHANGES and the opam files to reflect what we have in opam-repository atm.. please let me know if you'd like to postpone a mirage release (in case there should be something included which is not yet atm)!?
=> prepare for release

mirage.opam
This will avoid spurious CI failures until #924 is merged.
/cc #923
=> Add conflict with mirage-solo5 >= 0.4.0

lib/mirage.ml
similar to https://github.com/mirage/functoria/pull/157 -- generate opam-version 2 now...
the `build:true` is needed for technical reasons: otherwise ocamlfind/ocamlbuild tries to link the `ocaml` package which does not exist.
~~EDIT: i don't expect the CI to succeed here due to requiring the functoria change as well~~
=> opam2: specify ocaml as dependency instead of via available

.ocamlformat, .travis.yml, lib/mirage.ml, lib/mirage_impl_fs.ml, lib/mirage_impl_fs.mli, test/dune, test/test_generated_files.expected, test/test_generated_files.ml
We have to start from somewhere!
This sets up tests for the code generation in the FS module, and normalizes the code a bit:
- `ocamlformat` - I reused an existing config so that at least we have terminator sequences & vertical type declarations (this is not enforced in CI yet)
- rename `fs` to `t` & `typ`
As follow ups, I'll setup ppx codegen in a module that generates some nontrivial ocaml, and next I'll convert the rest at the same time if there's not much going on.
=> Test fs module

lib/mirage.ml, lib/mirage_key.ml
see https://github.com/mirage/mirage/issues/923#issuecomment-434789902 -- in short, the "mirage clean" is broken if you had a configured unikernel with `-t ukvm` around.
this unifies the two occurences of `ignore_dirs`.
=> mirage: unify ignore_dirs for configure and build, support -t ukvm again

mirage.opam
no need to keep this information a second time
=> remove conflicts from opam - mirage generates code with such lower bounds

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli
unfortunately, opam depext AFAICT doesn't support a local opam file, it needs
to get the opam file pinned
addresses #852
=> avoid opam pin during installation of dependencies in generated makefile

lib/mirage.ml
sorry for that. if CI passes, I'll merge and release 3.3.1.
=> regression in 3.3.0: opam install no longer gets --yes passed

lib_runtime/dune, lib_runtime/mirage_runtime.ml, mirage-runtime.opam
fewer dependencies are better, and split_on_char exists since 4.04.0 -- mirage depends on >=4.04.2.
most unikernels won't see an improvement in binary size, since they usually use parse-argv that depends (rightfully!) on Astring -- but we have the `no_argv` device -- if your unikernel is not interested in boot arguments that can leverage ~300kB of binary size.
no, I've no plans to remove the fmt and/or logs dependency from mirage-runtime ;)
=> Use String.split_on_char instead of Astring in mirage-runtime

lib/mirage_impl_mclock.ml, lib/mirage_impl_pclock.ml
i.e. all unikernels are fine with this. ref https://github.com/mirage/mirage-clock/pull/38 https://github.com/mirage/mirage-clock/pull/39 https://github.com/ocaml/opam-repository/pull/13207
=> mirage-clock 2.x only API change is type t = unit, which is fine with mirage

lib/mirage.mli, lib/mirage_impl_stackv4.ml, lib/mirage_impl_stackv4.mli, lib/mirage_key.ml, lib/mirage_key.mli
currently, when compiling for unix, the default network stack is the direct one -- unless `--net=socket` is provided. various unikernels contain the following boilerplate in the config.ml:
```OCaml
let net =
if_impl Key.is_unix
(socket_stackv4 [Ipaddr.V4.any])
(static_ipv4_stack ~config:address default_network)
```
to use the socket stack by default on unix. This is not a good idea in several aspects, including that now on unix it is no longer possible to configure a direct stack.
=> default to socket stack on unix and macosx when using generic_stackv4

lib_runtime/mirage_runtime.ml
as commented in https://github.com/mirage/mirage/pull/957#issuecomment-450776686, `String.split_on_char` does never return the empty list.
=> fix parsing of "-l debug" for log sources, as mentioned by @cfcs

lib/mirage_key.ml, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli, mirage-runtime.opam, mirage.opam
The problem I try to solve: a hello world (not stripped, no lto, hvt target) is on my machine 3MB in binary size. I investigated why this is the case. A major consumer of binary size is the sexplib library, which is required by the ocaml-ipaddr library at the moment.
Mirage itself also uses the s-expression conversion for arguments. This PR uses pp and of_string instead.
Once ipaddr will split its sexp usage into a separate library (as uri did recently, introducing uri.sexp), a resulting hello world unikernel will use only 2MB in binary size.
This PR is ready for review, and I'm interested in your feedback. At its current state, it assumes that "forall ip. of_string_exn (pp ip) = ip", is this reasonable? I tried to use `to_string` instead, but `Ipaddr.V6.to_string` has a different …
=> Use pp and of_string from Ipaddr modules instead of s-expressions

lib/mirage_impl_random.ml
this is already taken care of by nocrypto. this is also not needed here.
how zarith (and gmp) "cross-compilation" works at the moment:
zarith-freestanding(-xen) require gmp-freestanding(-xen), that uses the CFLAGS
of ocaml-freestanding(mirage-xen-posix) via pkg-config to compile zarith+gmp for
the desired target.
the above build (of the C artifacts) results in archive files
(libgmp-freestanding.a and libzarith-freestanding.a), which are installed via
opam. in addition, the META file of zarith is extended with
'freestanding_linkopts = "-lzarith-freestanding -L@gmp-freestanding -lgmp-freestanding"'
(similar for xen). this line is picked up by mirage (once zarith is in the
dependency cone, and the target is a solo5 one) via ocamlfind predicates to
link the final unikernel.
now, at build time …
=> avoid zarith-freestanding / zarith-xen build dependency

.travis-ci.sh, .travis.yml, lib/mirage.ml, lib/mirage_impl_arpv4.ml, lib/mirage_impl_ethernet.ml, lib/mirage_impl_ip.ml, lib/mirage_impl_network.ml, mirage-types-lwt.opam, mirage-types.opam
A brief list of changes:
- Ethernet encapsulation is done in Ethernet - currently done in Arp and IPv4 and IPv6 libraries
- MTU is passed from the network interface upwards - currently passed into the Ethernet layer
- Write buffer allocation is done by the network interface, which knows best about page boundary restrictions, etc. - currently done in IPv4, IPv6, ARP using Io_page.get 1
- write functions signature change throughout the stack up to Ip: the buffer to send is no longer given directly, instead a size argument and a fill function of type (buffer -> int).
- IPv4 applies fragmentation!
- no longer used function are removed
I did performance evaluation as follows (I'm pretty sure this is not exhaustive, and likely others have better ideas on how to actually do such a benchmark):
- …
=> [RFC] TCP/IP stack MTU, layering, and write allocation discipline changes

lib_runtime/mirage_runtime.ml
(regression introduced in 3.4.0, sorry)
=> fix -l \*:debug parsing regression (unintended behaviour change in b84dbcd1d)

.travis-ci.sh, .travis.yml, CHANGES.md, lib/mirage.ml, lib/mirage.mli, lib/mirage_impl_block.ml, lib/mirage_impl_block.mli, lib/mirage_impl_conduit_connector.ml, lib/mirage_impl_fs.ml, lib/mirage_impl_fs.mli, lib/mirage_impl_http.ml, lib/mirage_impl_ip.ml, lib/mirage_impl_kv.ml, lib/mirage_impl_kv.mli, lib/mirage_impl_kv_ro.ml, lib/mirage_impl_kv_ro.mli, lib/mirage_impl_mclock.ml, lib/mirage_impl_pclock.ml, lib/mirage_impl_qubesdb.ml, lib/mirage_impl_syslog.ml, lib/mirage_impl_syslog.mli, mirage-types-lwt.opam, mirage-types.opam, mirage.opam, types/mirage_types.ml, types/mirage_types_lwt.ml
this is the release engineering branch for 3.5.0. travis is supposed to succeed with the given remote and mirage-skeleton.
changes needed before a release are mainly a functoria Mirage_kv.RW device (plus merges in opam-repository, and a cohttp-mirage release). a **successful** mirage-dev travis job using this branch and the respective mirage-skeleton branch has run at: https://travis-ci.org/mirage/mirage-dev/builds/499798880
also, an entry for changes is necessary, certainly.
=> Releng 3.5.0

README.md, lib/mirage.ml, mirage-runtime.opam, mirage-types-lwt.opam, mirage-types.opam, mirage.opam
see https://github.com/mirage/mirage-kv/commit/3df5b30f240f675d8d95c94440825e013b7cfc2f for further information
with ocaml 4.04.2, mirage itself could be compiled, but any generated configured unikernel (opam file) would require 4.05.0 due to the mirage-kv >= 2.0.0 dependency of mirage-types, where mirage-kv requires 4.05.0.
=> require ocaml 4.05.0 or higher

lib/mirage_impl_tracing.ml
Needed once https://github.com/mirage/mirage-profile/pull/33 is released.
=> New tracing API no longer requires Gnt and Xs arguments

lib/mirage.ml
It should be fine to use mirage-xen 4.0.0.
=> Bump mirage-xen constraint to < 5.0.0

.travis.yml, lib/mirage.mli, lib/mirage_impl_conduit_connector.ml, lib/mirage_impl_resolver.ml, lib/mirage_impl_resolver.mli, lib/mirage_key.ml, lib/mirage_key.mli
this requires https://github.com/mirage/ocaml-conduit/pull/290 (which in turn requires a release of ocaml-dns, which will happen soon).
what this PR does:
- the Resolver_mirage.With_stack functor now requires a random device (to generate the identifier of the DNS packet) -- as usual, the `default_random` device is used (configurable via `--prng` configuration time parameter)
- two new command-line keywords are provided (both stages, configuration and runtime): `resolver` and `resolver-port` for configuring the resolver to use
=> revised resolver

lib/mirage.ml
Make the ocamlbuild invocation respect the mirage tool's verbosity
setting. As the default log level is Warning, this will result in quiet
builds by default; mirage build --verbose can be used to get an
equivalent of the old behaviour.
/cc @mirage/core
=> ocamlbuild: Respect verbosity, quiet by default

lib/mirage.ml
while testing and reading #1010 (esp. `at_exit` handlers), I discovered some inconsistencies in respect to unikernel teardown across the backends that I attempt to clean up here.
a) only with mirage-unix the `at_exit` is actually called (due to how binaries work on unix and that if main finishes, exit is called). MirageOS unikernels that terminate successfully (with exit code 0) never execute `at_exit` handlers. This is solved by calling `exit 0` after `OS.Main.run t`.
b) if `start` terminates abnormally, the different backends handle this slightly differently:
- mirage-unix executes the main task `t` in a `Lwt.catch`, where the exception handler `Logs.err` and calls `Lwt.return_unit` -- the exit code is always 0!
- mirage-solo5 and mirage-xen have a `try Lwt.poll () with exn -> ..`, …
=> exit 0 on successful termination

mirage.opam
for #1017 to pass, this has been applied to opam-repository at https://github.com/ocaml/opam-repository/pull/15364
=> relax mirage-runtime dependency to be in range 3.7.0 .. 3.8.0

lib/mirage_configure.ml
unfortunately I do not know since which git version the `rev-parse` is supported (pretty tricky to figure out). if this PR is fine, I plan to cherry-pick this commit on a 3.7.3 branch and cut a release 3.7.4 to "unbreak" mirage for people with old git installations.
the code in question is guarded - `find_git` is called in `configure_opam`, and if it errors this is handled gracefully, thus installations of 3.7.3 with an old git do _not_ lead to mirage that is not able to configure, just to mirage whose generated opam files are suboptimal and an error is presented on console (but return code of mirage is 0).
discussion how to get the current branch from git is at https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
=> configure, output opam: use git rev-parse instead of git branch --show-current (the latter requiring git 2.22+)

mirage.opam
This makes pinning to a `dev` version possible.
/cc @hannesm 
It's a mix between what we had before and your [fix](https://github.com/mirage/mirage/pull/1019): we have some slack to release mirage and mirage-runtime separately while keeping the upper-bound to a known existing version (the current one!)
=> Use `version` instead of hard-coding a non-existing upper-bound.

Makefile, test/f0/f0.ml, test/functoria-query/install.expected
The CI wasn't testing these tests anymore (as it switched to use `dune runtest` instead of `opam install -t`) so the breakage went unoticed.
These tests really need to be ported to dune (currently not possible to do this directly as they are recursively calling dune).
=> Fix functoria-runtime tests

.travis-ci.sh, lib/mirage.ml, lib/mirage.mli, lib/mirage_build.ml, lib/mirage_impl_conduit.ml, lib/mirage_impl_conduit_connector.ml, lib/mirage_impl_random.ml, lib/mirage_impl_random.mli, lib/mirage_key.ml, mirage.opam
please see discussion at https://github.com/mirage/mirage-crypto/issues/6
this is a PR against the 3.7 branch. this PR is backwards compatible, but the choice of `--prng` (=nocrypto/fortuna/stdlib) does not have any effect. instead, Fortuna will always be used.
=> Revise random

lib/mirage_impl_conduit.ml
this should have been part of 3.7.5, but is only a runtime issue (and thus wasn't detected in the release cycle -- sorry).
=> Fix conduit device

test/functoria/test.ml, test/functoria/test_key.ml, test/functoria/test_key.mli
The tests are extracted from #1085 and also test the `Arg.required` feature which was useful after all.
=> Add tests for Functoria.Key

lib/functoria/key.ml, lib/functoria/key.mli, test/functoria/test_key.ml
This allow to test if a key is present on the command-line (default values
are not added to the context anymore). Extracted from #1085 
/cc @Drup -- I don't think I have broken anything with this, but I'm not 100% sure :-)
=> Add Functoria.Key.find

lib/functoria/cli.ml
=> Fix help format for `<cmd> help --man-format=<x>`

lib/functoria/app.ml, lib/functoria/app.mli, lib/mirage/mirage.ml, lib/mirage/mirage_build.mli, test/f0/f0.ml
It is not used anymore (since config.ml got compiled with dune) and
none complained so I guess nobody used it. (note: it's still used by 
ocamlbuild to build the mirage projects)
Extracted from #1085
=> functoria: remove the [ignore_dirs] parameter

lib/functoria/app.ml, lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/info.ml, lib/functoria/info.mli, lib/mirage/mirage.mli, lib/mirage/mirage_configure.ml, lib/mirage/mirage_configure_libvirt.ml, lib/mirage/mirage_configure_libvirt.mli, lib/mirage/mirage_configure_xen.ml, lib/mirage/mirage_configure_xen.mli, lib/mirage/mirage_impl_block.ml, lib/mirage/mirage_impl_fs.ml, lib/mirage/mirage_impl_fs.mli, lib/mirage/mirage_impl_kv.ml, test/functoria-test/functoria_test.ml, test/functoria/e2e/test.ml, test/functoria/help/configure-help.out.expected, test/functoria/help/help-configure.out.expected, test/functoria/test_cli.ml, test/mirage-fat-shell-script/test.expected, test/mirage-fat-shell-script/test.ml, test/mirage/action/test.ml
This is not used anywhere and it makes it very hard to change the build logic.
This is extracted from #1085 
/cc @hannesm to double-check that this option is indeed not used/useful.
=> functoria: remove the --build-dir command-line option

lib/functoria/lib.ml, lib/functoria/tool.ml, test/functoria/query/files-configure.expected, test/functoria/tool/clean.err.expected, test/functoria/tool/configure-help.err.expected, test/functoria/tool/configure.err.expected
Extracted from #1085 and #1118
=> functoria: only `<tool> configure' should save the context cache

lib/functoria/cli.ml, test/functoria/help/dune
=> functoria: fix `configure --help' vs. `help configure'

lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/tool.ml, test/functoria/test_cli.ml, test/functoria/tool/configure-help.err.expected, test/functoria/tool/configure.err.expected
It is not necessary to pass all the arguments as the context has been cached
already.
Extracted from #1085
=> functoria: simplify re-exec of query commands

lib/mirage/mirage.ml, lib/mirage/mirage_key.ml, lib/mirage/mirage_key.mli
Follow-up of #1124 (and extracted from #1085)
=> mirage: --depext is now part of functoria

lib/functoria/cli.ml, test/functoria/query/Makefile.no-depext.expected, test/functoria/query/dune.inc, test/functoria/query/gen.ml, test/functoria/test_cli.ml, test/functoria/tool/configure-help.err.expected, test/functoria/tool/configure.err.expected
This should fix mirage-skeleton
=> functoria: use --depext by default (as the mirage tool did)

lib/functoria/context_cache.ml, lib/functoria/context_cache.mli, lib/functoria/lib.ml
This commit ensure that all commands are properly reading the cache
and merging it with the current command-line arguments.
From #1132
=> functoria: fix reading of cached arguments

test/functoria/help/build-help.expected, test/functoria/help/clean-help.expected, test/functoria/help/help-build.expected, test/functoria/help/help-clean.expected, test/mirage/help/build-help.expected, test/mirage/help/clean-help.expected, test/mirage/help/help-build.expected, test/mirage/help/help-clean.expected
This is needed because of the concurrent merges of #1133  and #1136
=> Fix promoted files

lib/functoria/action.ml, lib/functoria/action.mli, lib/functoria/tool.ml, test/functoria/test_action.ml, test/functoria/tool/ambiguous.err.expected, test/functoria/tool/ambiguous.expected, test/functoria/tool/build.err.expected, test/functoria/tool/build.expected, test/functoria/tool/clean.err.expected, test/functoria/tool/clean.expected, test/functoria/tool/configure-help.err.expected, test/functoria/tool/configure-help.expected, test/functoria/tool/configure.err.expected, test/functoria/tool/configure.expected, test/functoria/tool/default.err.expected, test/functoria/tool/default.expected, test/functoria/tool/describe.err.expected, test/functoria/tool/describe.expected, test/functoria/tool/help-configure.err.expected, test/functoria/tool/help-configure.expected, test/functoria/tool/help.err.expected, test/functoria/tool/help.expected, test/functoria/tool/query.err.expected, test/functoria/tool/query.expected, test/functoria/tool/simple-help.err.expected, test/functoria/tool/simple-help.expected
- By default, show stdout and stderr outputs;
- Also make sure that stderr/stdout are printed in case of errors.
=> functoria: do not hide sub-command outputs

lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/tool.ml, test/functoria/tool/ambiguous.err.expected, test/functoria/tool/ambiguous.expected, test/functoria/tool/build.err.expected, test/functoria/tool/build.expected, test/functoria/tool/clean.err.expected, test/functoria/tool/clean.expected, test/functoria/tool/configure-help.err.expected, test/functoria/tool/configure-help.expected, test/functoria/tool/configure.err.expected, test/functoria/tool/configure.expected, test/functoria/tool/default.err.expected, test/functoria/tool/default.expected, test/functoria/tool/describe.err.expected, test/functoria/tool/describe.expected, test/functoria/tool/help-configure.err.expected, test/functoria/tool/help-configure.expected, test/functoria/tool/help.err.expected, test/functoria/tool/help.expected, test/functoria/tool/query.err.expected, test/functoria/tool/query.expected, test/functoria/tool/simple-help.err.expected, test/functoria/tool/simple-help.expected
This fixes a regression introduced in #1145
=> Add the context files when the tool calls config.exe

lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/lib.ml, lib/functoria/tool.ml, test/functoria/test_cli.ml
The behavior was changed in https://github.com/dbuenzli/cmdliner/pull/111 so
it allows mirage to work with the dev version of cmdliner
=> Do not use $(mname) in the default value for CLI args

lib/functoria/key.ml, lib/functoria/key.mli, test/functoria/test_key.ml
While fixing this, I've noticed that there is a difference between 3.7 and the dev branch on how the device are distinguished:in 3.7 it using their name and keys; in the dev branch it's using a unique ID per device. That difference could possibly cause the duplication on some devices and might cause issue if their init function is called twice. This could be an issue for entropy/random devices as pointed out by @hannesm. I plan to investigate and address this in a separate PR.
=> Forward-port mirage/functoria#194

mirage-runtime.opam, mirage.opam
That'll unbreak the CI and will be reverted once all the mirage packages are updated.
=> Force ipaddr<5.0 temporary

lib/mirage.ml, lib/mirage_key.ml, lib/mirage_key.mli, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli
the main motivation behind this PR is that I'd like to pass on the GC strategy (since 4.10 there's best-fit) without recompiling the unikernel (since the OCaml runtime allows this as a rutime configurable option).
Now, I was as well unsatisfied with the hardcoded emission of `let _ = Printexc.record_backtrace true` into every `main.ml` file (which can now be safely removed :).
This PR defines several boot parameters (also configure stage --> both), mostly equivalent of what the `OCAMLRUNPARAM` environment variable allows. The documentation has been inspired by gc.mli and http://caml.inria.fr/pub/docs/manual-ocaml/runtime.html#s%3Aocamlrun-options .
For how the code is generated: my goal is to avoid repeating to hardcode defaults from the OCaml runtime, thus the keys are of type `int …
=> add ocaml runtime arguments (OCAMLRUNPARAM)

.ocamlformat, lib/mirage_build.ml, lib/mirage_impl_misc.ml, lib/mirage_impl_misc.mli
This was introduced in #636 for building mirage-entropy and nocrypto, but is no
longer used and necessary. The build ecosystem changed since then.
=> mirage build: remove predicate(...), which is no longer necessary

lib/mirage.ml, mirage-runtime.opam, mirage-types-lwt.opam, mirage-types.opam, mirage.opam
Several libraries used by mirage are supported on OCaml 4.08 and above, let's
bump the lower bound to 4.08.
=> opam, generated opam: bump lower bound to OCaml 4.08

.travis.yml, lib/mirage.ml, lib/mirage_build.ml, lib/mirage_configure.ml, lib/mirage_configure_solo5.ml, lib/mirage_configure_solo5.mli, lib/mirage_configure_xen.ml, lib/mirage_configure_xen.mli, lib/mirage_impl_argv.ml, lib/mirage_impl_block.ml, lib/mirage_impl_console.ml, lib/mirage_impl_ip.ml, lib/mirage_impl_network.ml, lib/mirage_impl_qubesdb.ml, lib/mirage_link.ml
This adapts the `mirage` front-end tool to the new Mirage/Xen platform stack (see mirage/mirage#1159).
User-visible changes:
- `.xe` (Xenserver) filegeneration has been removed, I have no way to test this.
- "Unknown" argument filtering in `Bootvar` / `argv` has been removed, this was causing problems and I do not know of any users apart from Qubes OS where this can be solved differently, see comments in mirage/mirage#1159.
Note that Xen unikernels now include a dummy Solo5 manifest to keep the rest of the build system and Solo5 layers happy; this does not contain any devices as they are not required and Xen device naming does not follow Solo5 requirements.
=> [Mirage 3.x] Port to new Mirage/Xen platform stack

lib/mirage_configure.ml
As reported in #1188, in case no git remote is specified (or no branch
is configured), git will complain to stderr "fatal: No such remote 'origin'".
The code in question is used to include a src url into the generated opam
file on a best-effort basis, and already handles errors (e.g. the unikernel is
not developed in a git repository) by using a dummy url.
=> redirect stderr to /dev/null when invoking git

lib/mirage_key.ml
unfortunately this slipped through the release 3.10.. it only affects users of `Mirage_key.Arg.ip_address` -- I'll do a 3.10.1 release
=> fix Mirage_key.Arg.ip_address (serialise emitted superfluous '.')

lib/mirage/mirage_key.ml
This PR fixes the ipv6 key, which has the wrong label (`ipv6_prefix`) so the generated code wouldn't build. 
The `ping6` mirage-skeleton unikernel is failing because of this:
```
File "key_gen.ml", line 103, characters 48-78:
103 |   (Functoria_runtime.Arg.opt (Cmdliner.Arg.some Mirage_runtime.Arg.ipv6_prefix) 
```
=> Fix ipv6 key

lib/functoria/action.ml, lib/functoria/action.mli, lib/functoria/context_cache.ml, lib/functoria/device.ml, lib/functoria/engine.ml, lib/functoria/filegen.ml, lib/functoria/functoria.ml, lib/functoria/lib.ml, lib/functoria/opam.ml, lib/functoria/tool.ml, lib/mirage/impl/mirage_impl_fs.ml, lib/mirage/impl/mirage_impl_kv.ml, lib/mirage/impl/mirage_impl_misc.ml, lib/mirage/impl/mirage_impl_tracing.ml, lib/mirage/mirage_build.ml, lib/mirage/mirage_clean.ml, lib/mirage/mirage_configure.ml, lib/mirage/target/mirage_target.ml, lib/mirage/target/solo5.ml, lib/mirage/target/unix.ml, test/f0/f0.ml, test/functoria-test/functoria_test.ml, test/functoria/test_action.ml
Instead of using infix operators, use custom `let*` / `let+` operators. This allows code to be written in a more _direct style_. 
(based on https://github.com/mirage/mirage/pull/1212)
=> Use let* syntax for the Action API

lib/functoria/lib.ml, lib/functoria/makefile.ml, lib/functoria/makefile.mli, lib/functoria/misc.ml, lib/functoria/misc.mli, test/functoria/query/run.t, test/mirage/query/config_dash_in_name.ml, test/mirage/query/dune, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
On top of https://github.com/mirage/mirage/pull/1251
Implement the workflow suggested in https://github.com/mirage/mirage/issues/1250.
* Separate Makefile `depends` target in three steps: `lock`, `depends` and `pull`.
* `make all` does all of them + `build` 
* The new `opam monorepo depext` command is used to install depexts from the lockfile
One question remains: what should be the behavior of `make` by default: `make all` or `make build` ? For now it's `make all`.
=> Simplify makefile

lib/functoria/lib.ml, lib/functoria/makefile.ml, lib/functoria/makefile.mli, lib/functoria/misc.ml, lib/functoria/misc.mli, test/mirage/query/config_dash_in_name.ml, test/mirage/query/dune, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
This PR fixes the first question of https://github.com/mirage/mirage/issues/1249
What it does is remove ocamlification of the name in `Config.v` and introduce _opamification_ for Makefile generation and opam file generation. _opamification_ is a less constrained transformation from arbitrary names to opam-friendly package names. 
First commit adds tests to highlight the changes. Second commit actually perform the changes.
=> Fix ocamlification of unikernel names

.ocamlformat, lib/functoria/action.ml, lib/mirage/mirage_key.ml, lib/mirage/target/solo5.ml, test/mirage/query/run-hvt.t
as seen on https://ci.mirage.io/pipelines/pr-372-mirage-4-mirage-mirage-dev/pr-372-mirage-4-mirage-mirage-dev-f4b813668ee45d2371dc75fc8f1890997ecdbe00/x86_64-debian-10-4.13/2022-01-07/114419-ocluster-build-203a20
otherwise e.g. freestanding 0.6.6 is installed (and build fails)
=> mirage: require ocaml-freestanding 0.7.0

mirage-runtime.opam
`mirage-runtime` requires the same version as `functoria-runtime`.
=> Lint mirage-runtime.opam file

lib/functoria/lib.ml, lib/functoria/lib.mli, lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_console.ml, lib/mirage/impl/mirage_impl_network.ml, lib/mirage/impl/mirage_impl_time.ml, lib/mirage/impl/mirage_impl_tracing.ml, lib/mirage/mirage.ml, lib/mirage/target/unix.ml, test/f0/f0.ml, test/functoria/e2e/lib/e2e.ml, test/mirage/query/run.t, test/mirage/random-unix/main.ml.expected, test/mirage/random-xen/main.ml.expected
From the MirageOS core meeting, we decided to delete the last _relicat_ about `mirage-os-shims`. Now, a target must provide its own module `OS` and it must be named/prefixed to avoid a clash of names (and unlock the ability to compile in the same universe multiples targets).
=> No common path & impl. about the OS module - each target implements their own modules

lib/functoria/makefile.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
The generated makefile rule was wrong, it was cd-ing into the build directory
thus making the location of the lock file incorrect (as it is relative to the
makefile position). Instead, we use the --root / -r option of opam-monorepo
to fetch the duniverse folder inside the build directory, without having to cd
into it.
=> Fix the pull step when the build directory is custom

lib/mirage/mirage.ml, test/mirage/query/run-hvt.t, test/mirage/query/run.t
According to OPAM and for a beta release, the minimal version
must be 4.0 instead of 4.0.0. Indeed, OPAM concludes that
4.0.0~beta1 < 4.0.0 (but 4.0.0~beta1 > 4.0).
Try to fix mirage/mirage-dev#381
=> Fix minimal version required for mirage{,-runtime}

lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_console.ml, lib/mirage/impl/mirage_impl_mclock.ml, lib/mirage/impl/mirage_impl_network.ml
See mirage/mirage-dev#385 which requires a `beta3` release.
=> Lint version of some packages according to their releases

lib/functoria/DSL.mli, lib/functoria/info.ml, lib/functoria/opam.ml, lib/functoria/package.ml, lib/functoria/package.mli
The `dev` version string that is added by default can mess with opam's version comparison.
For example `ppx_deriving_yaml` now requires `yaml < 3.0.1` but `yaml.dev` is considered higher than `yaml.3.0.1`.
This fixes the build of `mirage-www`: https://github.com/Julow/mirage-www/commit/8aad99becaf47ecbf78de37dd8748d264248a610
The `pin-depends` field is changed to:
```
pin-depends: [ ["yaml.3.0.0" "git+https://github.com/TheLortex/ocaml-yaml.git#7e1f117645ea10fbec2bd3dbbf0d8f581cce891f"]
]
```
=> Allow to specify version of pinned packages

lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_block.mli, lib/mirage/mirage.ml, lib/mirage/mirage.mli
`docteur` is close to be released. May be a good time to add it into our `mirage-skeleton`. This PR is a draft to have review about documentation. Currently, the workflow is simple:
- the user decide what he/she wants to download (it can be a remote Git repository or `file://path/`)
- the device (as `tar_archive`) makes the image _via_ dune
- we install the image (`disk` by default - Solo5 does not like `.`) into the `dist/` directory
- from `unix`, a simple launch is enough (the block device will `open "disk"` by itself)
- from `solo5`, we must pass `--block:disk=<path-to-the-disk-file>`
=> Add `docteur` device

lib/mirage/impl/mirage_impl_conduit.ml
=> require conduit 5.1.0+ (which does not result in an exception if the TLS handshake fals on the server side)

lib_runtime/functoria/functoria_runtime.ml, lib_runtime/functoria/functoria_runtime.mli
Retransmit the `opt_all` combinator into the `functoria-runtime` package to allow to use it into the generated `key_gen.ml`.
=> Add opt_all into the functoria-runtime package

lib/functoria/package.ml, test/functoria/test_package.ml
A fix for https://github.com/mirage/mirage/issues/1287
So this way, an invalid package name yields `Invalid_argument` at configure-time. We could add a hint (for example if there is a dot in the name) but at least the error is not propagated to opam-monorepo !
=> Check that the package name respects opam conventions

lib/mirage/impl/mirage_impl_dns.ml, lib/mirage/mirage.mli
It's a more user-friendly interface where the user don't need to give a default value of the timeout if he/she wants to define a `timeout` command-line argument.
=> The timeout argument of the dns-client device must be an optional int64

lib/mirage/impl/mirage_impl_network.ml
This includes #1036. mirage-net-unix 3.0.0 is PRed to opam-repository.
=> bump mirage-net-unix lower bound to the does-not-catch-exceptions

lib/mirage/mirage.ml, lib/mirage/mirage.mli
Related to mirage/mirage-tcpip#474. It helps us to start to implement protocols which expects only a TCP/IP stack. By this way, it easy to:
1) implement protocols regardless the UDP/IP stack
2) have an easy switch between `mirage-tcpip` which provides a full-stack and `utcp` which provides only a `Tcpip.Tcp.S`
=> Add tcpv4v6_of_stackv4v6

CHANGES.md, lib/mirage/impl/mirage_impl_git.ml, lib/mirage/mirage.ml, lib/mirage/mirage.mli
Re-open the PR to continue the discussion from #1283 and try to finalize it. For my point of view:
=> Add git devices

lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_console.ml, lib/mirage/impl/mirage_impl_mclock.ml, lib/mirage/impl/mirage_impl_network.ml, lib/mirage/impl/mirage_impl_pclock.ml, lib/mirage/target/solo5.ml, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t
Assume that `ocaml-solo5.0.8.0` is released (which should be just a GitHub rename), this PR wants to fix #1294. The rename can be quick or _clean_: indeed, we have several things which takes the `freestanding` name (such as the `dune`'s context, `ocamlfind`'s toolchain). What should be the best for us according to our deadline (/cc @mirage/core)?
_to test with_ https://github.com/mirage/mirage-dev/pull/387
=> Rename ocaml-freestanding to ocaml-solo5

lib/mirage/target/mirage_dune.ml, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
Only disable "[missing-mli] Missing interface file." as we are generating
a lot of .ml files without the associated mli files.
Replaces #1313
=> Use the same flags as dune

dune-project
Otherwise, we get:
```
- File "test/functoria/e2e/dune", line 18, characters 11-28:
- 18 |   (package functoria-runtime))
-                 ^^^^^^^^^^^^^^^^^
- Error: Dependency on an installed package requires at least (lang dune 2.9)
- (cd _build/default/test/functoria && ./test.exe)
```
When running the e2e tests.
=> Fix dune version in dune-project

lib/mirage/impl/mirage_impl_block.ml, lib/mirage/mirage.mli
This fix is related to the recent release of `docteur.0.0.5` where we are able to craft an image from a **relative** path.
=> Be able to make a docteur image from a relative path

lib/functoria/install.ml, lib/functoria/install.mli, lib/functoria/lib.ml, lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_block.mli, lib/mirage/mirage.ml, lib/mirage/mirage.mli, lib/mirage/target/solo5.ml, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t
A context is needed to explain this PR and it's related to #1323.
The goal is to let the user to define some JS files which will be produced by `js_of_ocaml`. Then, a block-device should be generated to the user which includes JS files. A concrete example is [pasteur](https://github.com/dinosaure/pasteur) where the JS script comes from an OCaml code - by this way, we are able to make a website only in OCaml 🚀 .
However, I encountered several problems specially about the "cross-compilation" context. Indeed, it's a non-sense to let the user to fetch and compile `js_of_ocaml` into our (current) Solo5 context. From such situation, we must precise that some artifacts needed for our unikernel (such as block-device) must be buildable only into the default context/with the host compiler.
This PR …
=> Build non-executable artifacts in the host context

.ocamlformat, lib/functoria/DSL.mli, lib/functoria/functoria.mli, lib/functoria/type.mli, lib/mirage/mirage.mli
This is a preview of the formatting of your project codebase with the upcoming `ocamlformat.0.21.0`. Note that this package is not yet released in opam (so the linting/formatting task of your CI won't pass), the formatting might also change slightly in the released version as we try to integrate feedback from our users.
The changes on this project are due to:
- the separators of codeblocks `{[]}` in doc-comments are now placed on their own line, this is the new syntax agreed upon with other tools handling odoc comments.
As always, we are happy to hear your feedback!  Thank you for using ocamlformat!
=> Preview: upgrade to ocamlformat.0.21.0

mirage.opam, test/opam-monorepo/lock.t
A simple `dune promote` with `opam-monorepo.0.3.2` (probably related with #1327)
=> Fix tests with opam-monorepo.0.3.2

lib/mirage/mirage.mli
I updated by looking at the deprecation comments in #1006 and by following the comment when installing `mirage-protocols`. There may be more dated references in the comments.
=> mirage.mli: update deprecated references

lib/mirage/target/solo5.ml, test/mirage/query/run-hvt.t
require ocaml-solo5 0.8.1 and mirage-solo5 0.9.0 and mirage-xen 8.0.0
as discussed in https://github.com/mirage/mirage-xen/pull/48
this PR may need to wait for https://github.com/ocaml/opam-repository/pull/21860 and https://github.com/ocaml/opam-repository/pull/21861
=> adapt to new released mirage-xen & mirage-solo5

.ocamlformat, lib/functoria/info.ml, lib/functoria/info.mli, lib/functoria/install.ml, lib/functoria/install.mli, lib/functoria/lib.ml, lib/functoria/opam.ml, lib/functoria/opam.mli, test/functoria-test/functoria_test.ml, test/functoria/query/run.t, test/mirage/action/test.ml, test/mirage/query/run-hvt.t, test/mirage/query/run.t
this is a draft to enable reproducible builds with mirageos 4.x
=> Reproducible

lib/functoria/lib.ml, test/functoria/query/run.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
this is useful so that the packages used via opam-monorepo to build the
unikernel have their external dependencies fulfilled.
please anyone (@samoht @dinosaure @TheLortex) who's interested in reviewing do a quick review -- with this change, I can finally compile (using orb) the static-website-tls example (well, https://github.com/mirage/ocaml-gmp/pull/15 is needed as well).
best and enjoy your holidays :)
=> generated opam file: also run depext-lockfile

lib/mirage/mirage.mli
the command line utility expects the file name first, the block size as second
argument.
=> mirage.mli: fix the chamelon example invocation

lib/mirage/impl/mirage_impl_reporter.ml, lib/mirage/impl/mirage_impl_reporter.mli, lib/mirage/mirage.mli, lib/mirage/mirage_key.ml, lib_runtime/mirage/mirage_runtime.ml, lib_runtime/mirage/mirage_runtime.mli
Also does not raise exceptions on unknown log levels.
Addresses #1273 and #1274
This is a breaking change. Most of it can be achieved in a non-breaking way also.
=> Mirage_runtim: allow more log levels

lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/context_cache.ml, lib/functoria/lib.ml, lib/functoria/tool.ml, test/functoria/context/config.ml, test/functoria/context/dune, test/functoria/context/run.t, test/functoria/context/z.context, test/functoria/tool/run.t
The two commits are fixing two separate issues:
Fixes https://github.com/mirage/mirage/issues/1344
Basically, the tool can create an invalid context cache file if the command is wrong, as a parse error will still trigger re-execution of the `config.exe`. However this `config.exe` will call into `Context_cache.peek` which will then fail with `Invalid cached configuration. Please run configure again.`. The fix is to simply let `peek` return `None` in that situation. 
Another solution might be to let `config.exe` store arguments the context cache only after verifying that it is valid. That means a bit of refactoring as the tool is currently the one in charge of it.
Currently, there's an `assert false` in `Cli.peek_args`:
```ocaml
let peek_args ?(with_setup = false) ~mname argv =
let args = …
```
=> Improve functoria cli

lib_runtime/mirage/mirage_runtime.ml
Avoid manual construction of Cmdliner.Arg.conv instances
=> mirage-runtime: use Logs.level_of_string and Logs.level_to_string

lib/functoria/install.mli, lib/mirage/impl/mirage_impl_conduit.ml, lib/mirage/impl/mirage_impl_resolver.ml, lib/mirage/impl/mirage_impl_resolver.mli, lib/mirage/mirage.mli, lib/mirage/mirage_key.ml, lib/mirage/mirage_key.mli
The parsing of nameserver list is delayed until runtime due to ease of creation of tls authenticator with ca-certs available. Also allow specifying multiple nameservers. The `resolver` and `resolver-port` keys are melded into one key `resolver` that also supports specifying TLS nameservers. The (complicated) format should be documented.
=> Update to Resolver_mirage changes

lib/mirage/mirage.mli
Pointed out by @Engil, it is difficult to get a description of the format required to define a specific nameserver. I have added documentation to explain the format of the latter to make it easier to use. (/cc @hannesm)
=> Improve the documentation about `generic_dns_client` and explain the format of the `nameserver` argument

lib/mirage/impl/mirage_impl_http.ml, lib/mirage/impl/mirage_impl_http.mli, lib/mirage/mirage.ml, lib/mirage/mirage.mli
https://mirage.io starts to use it and we continue to improve the support of HTTP, HTTPS and ALPN through the `paf.mirage` package. Several people asks to have an easy way to start an HTTP service without too much complexities (mainly about composition of functors). This new device helps the end-user to start from nothing a simple HTTP server and he/she is able to switch to an HTTP with TLS server or, moreover, an ALPN server which handles `http/1.1` and `h2` protocols through TLS.
A documentation was added to show a minimal example of how to make a HTTP server. Probably, we can improve the example with a simple "Hello World!".
=> Add a new device to be able to easily start an HTTP (including ALPN) server

lib/functoria/makefile.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
On macos, echo does not have a -e flag, which results in the -e and ansi escape sequences being printed literally. The printf command handles ansi escape sequences by default.
=> Replace 'echo -e' with 'printf' in makefiles

lib/mirage/impl/mirage_impl_git.ml, lib/mirage/impl/mirage_impl_http.ml, lib/mirage/impl/mirage_impl_http.mli, lib/mirage/impl/mirage_impl_mimic.ml, lib/mirage/mirage.ml, lib/mirage/mirage.mli
This PR rename the initial `git_client` used to create a witness which is able to initiate a Git connection to `mimic` and be able to re-use the same instance for an new introduced ALPN client (http/1.1 and h2).
The ALPN client is currently used by the Robur's opam-mirror unikernel and can be used in several contexts when the user wants to do an HTTP (http/1.1 or h2) requests with TLS.
The mimic device (specially the `mimic_happy_eyeballs` device) initiate an happy_eyeballs instance which can be used and re-used by several devices such as `git_client` devices or the new introduced `alpn_devices`.
This commit breaks some names and specially some unikernels like our Git example into our mirage-skeleton repository. The main change is the renaming of `git_happy_eyeballs` to …
=> Introduce an ALPN client and Mimic

lib/mirage/target/solo5.ml, test/mirage/query/run-hvt.t
It includes the fix about the MSA03: https://mirage.io/blog/MSA03
=> Enforce the usage of solo5.0.7.5 when we make unikernels

lib/mirage/target/solo5.ml, test/mirage/query/run-hvt.t
//cc @dinosaure I'm a bit confused why 0.8.8 should be there. From my perspective, any 0.Y may change API in 0.(Y + 1), so best to restrict to < 0.8.0 [this is done for other opam packages as well in this package].
=> adjust solo5 bound: use 0.8.0 as upper bound

test/opam-monorepo/mini-opam-overlays/packages/fmt/fmt.0.9.0+dune/opam, test/opam-monorepo/mini-opam-overlays/packages/zarith/zarith.1.12+dune+mirage/opam, test/opam-monorepo/mini-opam-repository/packages/dune/dune.3.0.0/opam, test/opam-monorepo/mini-opam-repository/packages/gmp/gmp.6.2.9+dune/opam, test/opam-monorepo/mini-opam-repository/packages/mirage-runtime/mirage-runtime.4.0.0/opam, test/opam-monorepo/mini-opam-repository/packages/ocaml-solo5/ocaml-solo5.0.8.0/opam, test/opam-monorepo/mini-opam-repository/packages/solo5/solo5.0.7.1/opam
In https://github.com/tarides/opam-monorepo/pull/355 opam-monorepo marked packages without build instructions as virtual (e.g. packages that are conf-packages, dependency-only packages, etc).
This requires that the dummy OPAM files used here also have `build` stanzas, otherwise they are considered virtual and skipped.
(The `dune` change is only for good measure for future-proofing, similar to the compiler `dune` is treated specially anyway)
=> Add `build` stanzas to packages that are supposed to be vendored

.vscode/settings.json, lib/mirage/impl/mirage_impl_git.ml, lib/mirage/mirage.ml, lib/mirage/mirage.mli
Issue : #1378 
Removed git_happy_eyeballs from
1. lib/mirage/impl/mirage_impl_git.ml
2. lib/mirage/mirage.ml
3. lib/mirage/mirage/mli 
git_happy_eyeballs has been deprecated, and should be deleted for the next release.
=> Removed deprecated device git_happy_eyeballs

lib/mirage/impl/mirage_impl_block.ml, lib/mirage/impl/mirage_impl_block.mli, lib/mirage/mirage.ml, lib/mirage/mirage.mli
In addition, `archive` is deprecated in favor of `tar_kv_ro` and `tar_kv_rw`.
=> Add tar_kv_ro and tar_kv_rw

lib/functoria/key.ml
If you try to define a key with the name `""` in config.ml an error is raised if the key becomes relevant. However, the key may not always be relevant if it depends on e.g. `is_solo5`. This change pushes the check earlier so the error doesn't depend on conditionals.
```
couldn't open output channel for key_gen file: Invalid_argument("")
```
=> Disallow empty key names

lib/mirage/mirage.ml, test/mirage/query/run-hvt.t, test/mirage/query/run.t
Dear developers,
This PR should solve https://github.com/tarides/opam-monorepo/issues/340 and permits to compile mirage unikernels with Ocaml5+.
The underlying issue was the `ocaml` package marked as opam-provided and thus removed from dependencies at https://github.com/tarides/opam-monorepo/blob/9cc963ce7bc91592a301feca1e2238bc17448bd8/lib/opam_solve.ml#L114 (This can be seen inside the solver: https://github.com/ocaml-opam/opam-0install-solver/issues/47). Therefore, as https://github.com/ocaml/opam-repository/blob/master/packages/base-domains/base-domains.base/opam have a dependency list which contains `ocaml` OR `ocaml-variants`, leave the solver only with `ocaml-variants` if we remove `ocaml`.
For the time being I moved ocaml to the `Monorepo` scope, this is why it now appears as …
=> fix opam-monorepo issue with Ocaml5+

functoria-runtime.opam, lib_runtime/functoria/dune, lib_runtime/mirage/dune, lib_runtime/mirage/mirage_runtime.ml, mirage-runtime.opam
To test with: https://github.com/mirage/mirage-skeleton/pull/354
functoria-runtime did not use Fmt at all, and mirage-runtime only at two occasions. Given that these opam packages are core to every MirageOS unikernels, let's minimize their dependency to the bare minimum.
=> mirage-runtime/functoria-runtime: remove dependency on Fmt

lib/functoria/impl.ml, lib/functoria/impl.mli, lib/mirage/mirage.ml, test/mirage/help/config.ml, test/mirage/job-no-device/config.ml, test/mirage/job-no-device/configure.t, test/mirage/job-no-device/dune, test/mirage/query/config_dash_in_name.ml
This ensures that toplevel expressions in the unikernels are properly evaluated.
Fixes #873 #1426
//cc @reynir
To test with: https://github.com/mirage/mirage-skeleton/pull/359
=> Fail if there are jobs registered without any arguments.

lib/mirage/mirage.mli
To test with: https://github.com/mirage/mirage-skeleton/pull/360
so it can safely be removed in an upcoming release. see https://github.com/mirage/mirage-skeleton/pull/360
the reasoning behind this is that "console" devices have been carried over since a long time, but the need for it, esp. with Logs and log reporters in place is not well funded: there is no `read` from a console, there's no information such as width and height (for 2d graphics this would be needed), plus there are nowadays mature ssh and telnet implementations for doing 2d ascii art.
The original xen console device, with frontend and backend, and supporting multiple consoles, was a nice thing -- but I cannot find a unikernel that uses that code. So, to wrap up, in a world/ecosystem where complexity is usually increased …
=> mirage: mark console as deprecated

lib/functoria/functoria.ml, lib/functoria/functoria.mli, lib/functoria/key.ml, lib/functoria/key.mli, lib/functoria/lib.ml, lib/mirage/mirage_key.ml, test/functoria/e2e/help.t, test/functoria/gen-2/key_gen.ml.expected, test/functoria/help/build.t, test/functoria/help/clean.t, test/functoria/help/configure-o.t, test/functoria/help/configure.t, test/functoria/help/describe.t, test/functoria/help/query.t, test/functoria/lib/run.t, test/functoria/tool/run.t, test/mirage/help/build.t, test/mirage/help/clean.t, test/mirage/help/configure-o.t, test/mirage/help/configure.t, test/mirage/help/describe.t, test/mirage/help/query.t
This doesn't seem to be used anymore - it was a great initial feature to have initially to migrate from previous version of mirage, but it doesn't seem to be useful anymore. So let's remove it :-)
On top of #1435
=> Remove Key.Alias

lib/functoria/lib.ml, lib/functoria/lib.mli, lib/mirage/mirage.ml, lib/mirage/mirage.mli, test/f0/f0.mli, test/functoria/e2e/app/config.ml, test/functoria/e2e/lib/e2e.mli, test/functoria/help/config.ml, test/functoria/query/config.ml, test/mirage/help/config.ml, test/mirage/job-no-device-behind-if/config.ml, test/mirage/job-no-device/config.ml, test/mirage/query/config.ml, test/mirage/query/config_dash_in_name.ml
To test with: https://github.com/mirage/mirage-skeleton/pull/362
~~Once mirage 4.4.0 is merged into opam-repository, we'll be lucky and the CI may pass.~~
In the meantime, let me please know whether this is a bad idea or completely stupid. Thanks a lot.
=> Slim register function arguments

lib/functoria/dune.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
I guess this was forgotten in 22e7545acff8f3b79c2f955ad899fc326f71466e (and 9888bdff50274bf59270bdaf2a9cf14704e00f39).
=> Bump the dune version number generated in dune-project

lib/functoria/key.ml, lib/functoria/key.mli, lib/functoria/lib.ml, lib/functoria/tool.ml, test/functoria/test_key.ml, test/mirage/action/test.ml
In practice none is using those required keys anyway.
=> refactor: remove some complexity about handling of required keys

lib/functoria/key.ml, lib/functoria/key.mli, lib/functoria/lib.ml, lib/functoria/tool.ml
=> refactor: remove unused arguments from Key.context 

mirage-runtime.opam
//cc @samoht based on his work #1437
=> mirage-runtime.opam: avoid ipaddr dependency

lib/functoria/makefile.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
as discussed in https://stackoverflow.com/questions/54039983/print-bold-or-colored-text-from-makefile-rule
=> use \033 instead of \e for ansi escape sequences

lib/functoria/tool.ml, lib/functoria/tool.mli, test/functoria/test.ml, test/functoria/test_version.ml, test/functoria/test_version.mli, test/functoria/tool/run.t
Please take a look at the second commit:
check in mirage configure for a version lower bound in config.ml
If the first line of config.ml contains:
(* mirage >= a.b.c *) -- an OCaml comment
Then, a.b.c.d is checked to be smaller or equal the current version. This allows
within configure to error out early with a reasonable error message if a too old
mirage is attempted to be used with a unikernel.
Addresses #1381
I'm pretty sure this can be "optimized", but tbh I waded through the "action.ml" and was unable to figure out the purpose and value (instead of directly calling Bos). I hope someone can shed some light into why it is there.
Of course I'm happy for review and feedback on this PR.
//cc @samoht @TheLortex
~~EDIT: it is completely unclear to me why the mirage-CI fails with the "job …
=> Allow a mirage version in config.ml

lib/mirage/impl/mirage_impl_stack.ml, lib/mirage/impl/mirage_impl_stack.mli, lib/mirage/mirage.mli
this allows to more easily test utcp. since it is an optional argument, it won't break existing unikernels.
=> allow passing a tcp to the direct_stackv4v6

lib/mirage/mirage_key.ml, test/mirage/describe/run.t
OCaml since 4.13 uses best fit as default, but MirageOS never updated...  Thus now, if --allocation-policy is not specified, it got overwritten with next-fit (which is inferior).
=> default to best-fit allocation policy

lib/functoria/makefile.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
Reverts mirage/mirage#1462
The issue is outlined in #1476 -- with the code as is, the `opam install --deps-only $<` pin-depends everything (even those packages only meant for the `duniverse`. Let's revert that commit, and suffer from #1415
=> Revert "use the .opam.locked file for installing the switch dependencies"

lib/mirage/mirage_key.ml, lib_runtime/mirage/mirage_runtime.ml, test/mirage/help/clean.t, test/mirage/help/configure-o.t, test/mirage/help/configure.t, test/mirage/help/describe.t, test/mirage/help/query.t
This should make it easier to maintain doc strings.
Downsides are:
- phrasings are changed slightly
- the text is styled differently: instead of italic (or underline in my system) the values are rendered bold.
=> Use Cmdliner.Arg.doc_alts_enum

lib_runtime/mirage/mirage_runtime.ml
Previously, there were some missing, and appearing in the "OPTIONS".
=> Put runtime keys into "UNIKERNEL PARAMETERS" section

lib_runtime/mirage/mirage_runtime.mli
Previously, they were part of the Arg submodule. Now they're in their own Conv module. The reason is that mirage-monitoring uses this value for dynamically adjusting the log level.
=> mirage_runtime: restore converters for log_threshold and allocation_policy

lib_runtime/mirage/mirage_runtime.ml, lib_runtime/mirage/mirage_runtime.mli
previously, the rendered `--help` included `@` characters
=> fix log_threshold documentation

lib/functoria/lib.ml, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
This ensures that the tests are actually testing the right thing (and fix the tests).
that was initially part of #1493 but is actually an independent fix.
=> Fix `config.exe query` to use the same code path as code generation

lib/functoria/lib.ml, test/functoria/e2e/configure.t, test/functoria/query/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run.t
This will help to get better locations in error messages.
This is on-top of #1499 and extracted from #1493
=> Add line directives to OCaml files that are copied around

CHANGES.md, lib/functoria/functoria.ml, lib/functoria/functoria.mli, lib/functoria/job.ml, lib/functoria/job.mli, lib/functoria/lib.ml, lib/mirage/mirage.ml, lib/mirage/mirage.mli, test/functoria/gen-1/test.ml, test/functoria/gen-2/test.ml, test/mirage/info_gen/test.ml, test/mirage/random-unix/test.ml
=> Rename DSL.keys to DSL.runtime_args

CHANGES.md, lib/devices/target.ml, test/mirage/query/run-hvt.t
Dear devs, this PR is needed to avoid the unwanted selection of `ocaml-solo5` where an issue about fast memory usage value was present (https://github.com/mirage/ocaml-solo5/releases/tag/v0.8.2).
Best.
=> bump min ocaml-solo5 to avoid fast memory usage error

lib/mirage.mli
Update the code blocks in `mirage.mli` that use the old Key API.
=> doc: Update inline examples to Runtime_arg

lib/devices/key.ml, lib/devices/key.mli, lib/devices/stack.ml, lib/devices/stack.mli, lib/mirage.mli
the native ocaml stack can be used by passing "OCaml" or "direct".
over time, the confusion of "direct" has escalated. it is kept for backwards compatibility
//cc @pitag-ha
=> add the options to specify "host" (and "socket") for the host system network stack

lib/functoria/device.ml, lib/functoria/lib.mli, lib/mirage.ml, test/functoria/e2e/errors.t, test/functoria/e2e/lib/e2e.ml, test/mirage/random/run.t
This allows to catch subtle bugs caused by partial applications or by returning 'unit Lwt.t Lwt.t' using the type-system.
=> functoria: Constraint the start function to 'unit Lwt.t'

.ocamlformat
there's no change, but this will remove the need from changing it in a bunch of PRs.
=> update ocamlformat to 0.26.2

lib_runtime/functoria/functoria_runtime.ml
See #1248 @samoht @patricoferris @pitag-ha
Of course, happy to improve the text. But since this is a pretty common issue, I'm happy to have such a hint.
=> On a `Term error from Cmdliner, print a Hint about how to pass a space

RELEASE.md
First draft, review welcome /cc @mirage/core
=> Add a new draft to help with the release

lib/functoria/runtime_arg.ml, test/mirage/random/run.t
Fixes codes that use an arg call as an argument to a function:
code ~pos:__POS__ "f ~arg:%a"
Runtime_arg.call my_arg
=> functoria: Quote Runtime_arg.call

lib/functoria/info.ml, lib/functoria/info.mli, lib/functoria/lib.ml, lib/functoria/opam.ml, lib/functoria/opam.mli, test/mirage/action/test.ml, test/mirage/query/run-hvt.t, test/mirage/query/run.t
Previously, `sh -exc 'cd subdir && mirage build'` was used in the generated opam file as build command. Since #1404 got merged and released, the mirage build subcommand does no longer exist.
In the opam file, now "make build" is used instead.
=> fix generated opam file - the build rule is now `make "-Csubdir" "build"

lib/devices/argv.ml, lib/functoria/package.ml, lib/functoria/package.mli, test/mirage/describe/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run-noop.t, test/mirage/query/run.t, test/mirage/random/run.t
I found an even simpler example than "mirage-time" in respect to "how to use dune variants": boot parameters.
We used to have mirage-bootvar-xen, mirage-bootvar-unix, mirage-bootvar-solo5, and the parse-argv opam packages that were all involved.
Now, I created (retaining history) the single repository https://github.com/mirage/mirage-bootvar. This uses dune variants, the default is the unix implementation.
What is interesting about bootvar is that no one bothered to functorize it ;) Also, it shows how a unikernel could still decide to use "no_argv", bypassing any dune variant restrictions (I'm not sure whether this is desirable, but it is possible -- this also sheds some light that we could use configure-time keys to select some other implementation).
Anyways, this is much simpler than …
=> Consolidate mirage bootvar

lib/devices/ethernet.ml, lib/devices/ethernet.mli, lib/devices/stack.ml, lib/mirage.ml, lib/mirage.mli, test/mirage/random/run.t
To be used with https://github.com/mirage/mirage-skeleton/pull/396
Mark Mirage.etif as deprecated
=> Provide Mirage.ethif as an alias for Mirage.etif

lib/devices/ip.ml, lib/devices/qubesdb.ml, lib/mirage.ml
/cc @hannesm, I'm not sure that it's enough for your recent change about tcpip. At least, this change is required for `qubes-miragevpn`.
=> Upgrade the tool to use tcpip.8.1.0 and mirage-qubes.0.10.0

lib/functoria/impl.ml, test/mirage/job-no-device-arg/config.ml, test/mirage/job-no-device-arg/configure.t, test/mirage/job-no-device-arg/dune
This adds a test case (initially failing) where a device with some runtime arguments should not fail the `configure` stage.
The reasoning is: we really need to check that execution is delayed (i.e. it is not `let start = ...`, but more `let start _ = ...`).
Previously, we only checked for `args` -- which are the functor applications. Now, we also check for extra_deps - which are passed as arguments - and furthermore we check whether runtime_args is empty. And only in this case, where all of the three things are empty, and in addition we're not at the `noop` job, we raise an error.
Addresses @samoht comment on https://github.com/mirage/mirage/pull/1529#discussion_r1604834773
=> job with no arguments, check a bit more thoroughly

CHANGES.md, lib/functoria/DSL.ml, lib/functoria/DSL.mli
This PR reintroduce the `deps` argument into the `main` to be able to track a dependency which needs to be built by `dune` but we don't want to generate a module/functor from it. It's actually used by `pasteur` to track some JS files generated by `js_of_ocaml` and packed with `docteur` (to make a disk image).
=> Re-introduce deps which can be useful to track dependencies which need to be built but not used to apply a functor

lib/functoria/opam.ml, test/mirage/random/run-opam-git.t
It seems `ssh://` urls are relative when they otherwise look absolute, see e.g. https://github.com/ocaml/opam/issues/3382. I guess an absolute path is `ssh://user@host//absolute/path` i.e. a double leading slash.
Closes #1563.
Draft PR while I look into how we can test this.
=> opam src url: path includes leading slash

test/mirage/random/run-opam-git.t
The test was added in #1564 while #1566 was merged first adding a new warning. This updates the expected output of the test from #1564 with the warning and main should no longer error.
=> Update test with new warning

lib/functoria/dune.ml, test/functoria/e2e/errors.t
This gives better error messages when using a config.ml whose name is *not* config.ml, e.g. errors/in_device.ml.
=> Use copy# for config.ml

lib_runtime/functoria/functoria_runtime.ml
there are two kinds of errors: we call `get` too early, or `register` too late. Separate them to avoid clunky errors (see https://github.com/mirage/mirage/issues/1572#issuecomment-2396279621)
=> improve runtime argument error messages

lib/functoria/runtime_arg.ml, lib_runtime/functoria/functoria_runtime.ml, lib_runtime/functoria/functoria_runtime.mli, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli, test/mirage/random/run.t
The name `Mirage_runtime.register` is slightly too generic in my opinion.
=> provide Mirage_runtime.register_arg, deprecate Mirage_runtime.register

lib_runtime/mirage_runtime.ml
Enumerate the log levels so the caller doesn't have to guess if it's "warn" or "warning".
=> Mirage_runtime.logs: explain the log levels

lib/devices/runtime_arg.ml, lib/devices/runtime_arg.mli, lib/mirage.ml, lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli, test/mirage/describe/run.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run-noop.t, test/mirage/query/run.t, test/mirage/random/run.t
A special entry function, `configure_ocaml_runtime`, is defined in Mirage_runtime and run by mirage.ml.
This reduces the code generated in main.ml drastically.
=> OCaml runtime arguments are now in cmdliner-stdlib

lib_runtime/mirage_runtime.mli
and disable ocamlformat here locally
cc @reynir
=> add parens around the return value of register/register_arg

lib_runtime/functoria/functoria_runtime.ml, lib_runtime/mirage_runtime.ml
Runtime argument getters may be called before `Printexc.record_backtrace` is called - therefore we call it just before raising in order to get a nice backtrace.
For context see https://github.com/mirage/mirage-skeleton/pull/405#discussion_r1797009524
=> Add a call to Printexc.record_backtrace

lib_runtime/mirage_runtime.ml, lib_runtime/mirage_runtime.mli, lib_runtime/mirage_runtime_network.ml
fixes #1587
<details>
<summary>Manpage before this change</summary>
```
NAME
caldav
SYNOPSIS
caldav [OPTION]…
OPTIONS
--admin-password=STRING
Password for the administrator.
--http=PORT
Listening HTTP port.
--https=PORT
Listening HTTPS port.
--name=STRING, --host=STRING (required)
Hostname to use.
--remote=REMOTE (required)
Location of calendar data. Use suffix #foo to specify branch
'foo'.
--tls-proxy
TLS proxy in front (use https://<hostname> as base url).
--tofu
If a user does not exist, create them and give them a new
calendar.
NETWORK OPTIONS
--accept-router-advertisements=VAL (absent=true)
Accept router advertisements for the unikernel.
--dns_cache_size=DNS-CACHE-SIZE
DNS cache size
--dns_servers=DNS-SERVER
DNS servers (default to anycast.censurfridns.dk)
--dns_timeout=DNS-TIMEOUT …
```
=> separate DNS, happy-eyeballs, SSH, TLS, HTTP arguments into separate man page sections

lib/devices/ip.mli, lib/mirage.ml, lib/mirage.mli, test/mirage/random/run.t
Dear developers,
While working with the mirage-nat example, I tried to configure the public interface with DHCP, but it failed because `ipv4_of_dhcp` is not currently exported. This PR aims to add it.
`dune runtest` works fine, ~~except for the message `Error (warning 32 [unused-value-declaration]): unused value ipv4_of_dhcp.` but I don't know where I should use it :( ~~ EDIT: It was a redundant declaration, I also fixed line numbers in the tests with the additional line.
I'd be happy to change anything that isn't good enough :)
Best,
=> add DHCP device

lib/devices/runtime_arg.ml, lib/devices/runtime_arg.mli, lib/devices/syslog.ml, lib/devices/syslog.mli, lib/mirage.ml, lib/mirage.mli, lib_runtime/mirage_runtime_network.ml, lib_runtime/mirage_runtime_network.mli, test/mirage/random/run.t, test/mirage/warn-etif/config.ml
this removes the type syslog_config, and introduces boot parameters for your syslog configuration
also, mirage-monitoring is integrated into the possible mirage devices
----
The goal is to reduce the amount of code in `config.ml` across the unikernels that we use. Now, the approach to provide boot parameters for configuration instead of hardcoded values is now applied to syslog as well.
Bits to be upstreamed are:
```OCaml
let enable_monitoring =
let doc = Key.Arg.info
~doc:"Enable monitoring (syslog, metrics to influx, log level, statmemprof tracing)"
[ "enable-monitoring" ]
in
Key.(create "enable-monitoring" Arg.(flag doc))
let management_stack =
if_impl
(Key.value enable_monitoring)
(generic_stackv4v6 ~group:"management" (netif ~group:"management" "management"))
stack
let …
```
=> revise syslog, add monitoring

lib/devices/target.ml, lib/functoria/lib.ml, lib/functoria/makefile.ml, lib/functoria/makefile.mli, test/functoria/e2e/build.t, test/functoria/e2e/cache.t, test/functoria/e2e/keys.t, test/mirage/job-no-device-arg/configure.t, test/mirage/query/run-dash_in_name.t, test/mirage/query/run-hvt.t, test/mirage/query/run-noop.t, test/mirage/query/run.t, test/mirage/random/run-opam-git.t, test/mirage/random/run.t, test/mirage/warn-etif/run.t
It gives some hints to the user what they should do next.
The only thing slightly worrying is that the cram test cases have the log message two times - any hints why this is the case?
----
We could after the `build` improve depending on the target, if we would have access to the target. But I have a tough time to figure out how to pass this information through.
So, this is ready for review :D
=> Emit output what to do next. This fixes #921

lib_runtime/mirage_runtime.mli
It seems headers require a space after the comment, e.g.:
(** {2 Header} *)
let _ = ...
instead of:
(** {2 Header} *)
let _ = ...
The last two functions also didn't belong to the "exit codes" header, so add a more meaningful header for those.
=> Fix Mirage_runtime documentation headers

lib/devices/ip.ml, lib/devices/ip.mli, lib/devices/stack.ml, lib/devices/stack.mli, lib/devices/tcp.ml, lib/devices/tcp.mli, lib/devices/udp.ml, lib/devices/udp.mli, lib/mirage.ml, lib/mirage.mli, test/mirage/random/run.t, test/mirage/warn-etif/config.ml
The main objective is to reduce our code. And do not expose things that have turned up to be not used at all.
This removes some exports of some "stacks", which I haven't found any use of. If there's somewhere a use of these things, please let me know and we can re-add them. The direct_stackv4v6 is used in unikernels that use uTCP.
Also, the types ipv4_config and ipv6_config have been removed. I couldn't find any use of them.
=> Remove some stack exports

lib/devices/key.ml, lib/functoria/cli.ml, lib/functoria/cli.mli, lib/functoria/key.ml, lib/functoria/key.mli, lib/functoria/tool.ml, mirage.opam, test/functoria/e2e/configure.t, test/functoria/e2e/context.t, test/functoria/e2e/context/config.ml, test/functoria/e2e/run.t, test/functoria/test_cli.ml
in contrast to #1604, here the tests are running. Turns out, some testcases used no longer available cmdliner functionality, and the "expect tests" used shortforms of the arguments (i.e. `package` instead of `packages`). Furthermore, functoria embedded a `--context` argument to argv, while it should be `--context-file`.
I understand that capturing cmdliner output is something @dbuenzli is against, and I agree with him -- but I've no other idea for these "e2e" tests. So I'll let them be there.
=> upgrade to cmdliner 2.0
